In [1]:
library(ggplot2)
library(dtplyr)
library(tidyverse)
library(glue)
library(arrow)
library(patchwork)
library(data.table)
library("jsonlite")
library(ggthemes)
library(stringr)
library(ggtext)
library(ggdist)
library(boot)
library(dplyr)
library(Hmisc)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ tibble  3.2.1     ✔ dplyr   1.1.0
✔ tidyr   1.3.0     ✔ stringr 1.5.0
✔ readr   2.1.3     ✔ forcats 1.0.0
✔ purrr   1.0.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

Attaching package: ‘arrow’


The following object is masked from ‘package:utils’:

    timestamp



Attaching package: ‘data.table’


The following objects are masked from ‘package:dplyr’:

    between, first, last


The following object is masked from ‘package:purrr’:

    transpose



Attaching package: ‘jsonlite’


The following object is masked from ‘package:purrr’:

    flatten


Loading required package: lattice


Attaching package: ‘lattice’


The following object is masked from ‘package:boot’:

    melanoma


Loading required package: survival


Attaching package: ‘survival’


The following object is masked from ‘package:boot’:

    aml


Loading required package: Formula


Attaching package: ‘Hmisc’


The following objects are masked from ‘package:dplyr’:

    src, summarize


The following objects are masked from ‘package:base’:

    format.pval, units

In [2]:
base_path = "/sc-projects/sc-proj-ukb-cvd/results/projects/22_medical_records/data/220823_allofus/230502_revision"
base_path

[1] "/sc-projects/sc-proj-ukb-cvd/results/projects/22_medical_records/data/220823_allofus/230502_revision"

In [3]:
base_size = 8
title_size = 10
facet_size = 9
geom_text_size=3
theme_set(theme_classic(base_size = base_size) +
          theme(strip.background = element_blank(), plot.title=element_text(size=title_size, hjust=0),
                strip.text.x = element_text(size = facet_size),axis.title=element_text(size=10), axis.text=element_text(size=8, color="black"),
                legend.position="bottom", axis.line = element_line(size = 0.2), axis.ticks=element_line(size=0.2), panel.grid.major.y=element_line()))

Warning message:
“The `size` argument of `element_line()` is deprecated as of ggplot2 3.4.0.
ℹ Please use the `linewidth` argument instead.”

In [4]:
endpoint_defs = arrow::read_feather(glue("{base_path}/phecode_defs_220306.feather")) %>% arrange(endpoint)
endpoints_md = fread(glue("{base_path}/endpoints.csv"), colClasses=c("phecode"="character"))
endpoints = sort(endpoints_md$endpoint)

glue("{base_path}/phecode_defs_220306.feather")

/sc-projects/sc-proj-ukb-cvd/results/projects/22_medical_records/data/220823_allofus/230502_revision/phecode_defs_220306.feather

In [52]:
c(c("No UBR categorization", "Age >= 65"), c("No UBR categorization", "Annual income < $25k"))

[1] "No UBR categorization" "Age >= 65"             "No UBR categorization"
[4] "Annual income < $25k"

In [42]:
install.packages("PMCMRplus")

also installing the dependencies ‘gmp’, ‘Rmpfr’


Warning message in install.packages("PMCMRplus"):
“installation of package ‘gmp’ had non-zero exit status”
Warning message in install.packages("PMCMRplus"):
“installation of package ‘Rmpfr’ had non-zero exit status”
Warning message in install.packages("PMCMRplus"):
“installation of package ‘PMCMRplus’ had non-zero exit status”
Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

In [36]:
install.packages("ggsignif")

Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

In [37]:
library(ggstatsplot)
library(ggsignif)

You can cite this package as:
     Patil, I. (2021). Visualizations with statistical details: The 'ggstatsplot' approach.
     Journal of Open Source Software, 6(61), 3167, doi:10.21105/joss.03167


Attaching package: ‘ggstatsplot’


The following object is masked from ‘package:data.table’:

    :=

In [ ]:


  geom_boxplot() + 
  #stat_halfeye(side='left', scale=0.5) + 
  coord_cartesian(ylim=c(0.7, 0.95), clip = "on")+
  #stat_dotsinterval(side = "right", scale = 0.5, slab_size = NA) +
  scale_fill_brewer(palette="Set1") + 
  labs(x="Group", y="C-Index") + 
    theme(axis.title.x=element_blank(),
      panel.grid.major=element_blank(),
      strip.text = element_text(angle=270, hjust=1)
    ) +
    theme(legend.position="none") + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10))

In [9]:
results %>%
    mutate(Group=factor(Group)) %>%
    group_by(Group) %>%
    median_qi(cindex, .width = 0.95)

  Group                           cindex    .lower    .upper    .width .point
1 Age >= 65                       0.6701482 0.5421154 0.8245080 0.95   median
2 Annual income < $25k            0.7119549 0.5513737 0.8567299 0.95   median
3 At least one UBR categorization 0.7066735 0.5581413 0.8569858 0.95   median
4 Entire population               0.7036726 0.5607214 0.8595672 0.95   median
5 Less than high school education 0.7104032 0.5334177 0.8744769 0.95   median
6 No UBR categorization           0.6891180 0.5407752 0.8686168 0.95   median
7 Non-white or Hispanic/Latino    0.7133847 0.5500133 0.8687870 0.95   median
8 Sexual and gender minorities    0.7054237 0.5516209 0.8704998 0.95   median
  .interval
1 qi
2 qi
3 qi
4 qi
5 qi
6 qi
7 qi
8 qi

In [10]:
results[, list(list(boot(.SD, stat, R = 10))), by = Group]$V1

ERROR: Error in boot(.SD, stat, R = 10): no data in call to 'boot'

In [ ]:
  results %>%
    group_by(Group) %>% 
    bootstrap(., 10) %>% 
    do(tidy(median(cindex)))

ERROR: Error in bootstrap(., 10): could not find function "bootstrap"

In [ ]:
install.packages(groupwiseMedian)
library(groupwiseMedian)

ERROR: Error in install.packages(groupwiseMedian): object 'groupwiseMedian' not found

In [ ]:
devtools::install_github("DavisVaughan/strapgod")

ERROR: Error in loadNamespace(name): there is no package called ‘devtools’

In [ ]:
install.packages('tidymodels')
library(tidymodels)

also installing the dependencies ‘warp’, ‘lhs’, ‘DiceDesign’, ‘furrr’, ‘slider’, ‘GPfit’, ‘conflicted’, ‘dials’, ‘infer’, ‘modeldata’, ‘parsnip’, ‘rsample’, ‘tune’, ‘workflows’, ‘workflowsets’, ‘yardstick’


Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

── Attaching packages ────────────────────────────────────── tidymodels 1.0.0 ──

✔ broom        1.0.0     ✔ rsample      1.1.0
✔ dials        1.0.0     ✔ tune         1.0.0
✔ infer        1.0.3     ✔ workflows    1.1.0
✔ modeldata    1.0.1     ✔ workflowsets 1.0.0
✔ parsnip      1.0.1     ✔ yardstick    1.1.0
✔ recipes      1.0.1

Warning message:
“package ‘broom’ was built under R version 4.0.5”
Warning message:
“package ‘scales’ was built under R version 4.0.5”
Warning message:
“package ‘recipes’ was built under R version 4.0.5”
── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
✖ data.table::between()   masks dplyr::between()
✖ scales::discard()       masks purrr::discard()
✖ dplyr::filter()         masks stats::filter()
✖ data.table::first()     masks dplyr::first()
✖ recipes::fixed()        masks stringr::fixed()
✖ jsonlite::flatten()     masks purrr::flatten()
✖ dplyr::lag()            masks stats::lag()
✖ data.table::last()      masks dplyr::last()
✖ yardstick::spec()       masks readr::spec()
✖ Hmisc::src()            masks dplyr::src()
✖ recipes::step()         masks stats::step()
✖ Hmisc::summarize()      masks dplyr::summarize()
✖ parsnip::translate()    masks Hmisc::translate()
✖ data.table::transpose() masks purrr::transpose()
• Use tidymodels_prefer() to resolve common conflicts.

In [ ]:
median_as_tibble <- function(split) {
  dat <- analysis(split)
  tibble(
    term = "median",
    estimate = median(dat$cindex),
    # don't know the analytical std.err so no t-intervals
    std.err = NA_real_
  )
}

results %>%
    filter(Group == 'Entire population') %>%
    bootstraps(times = 1000, apparent = TRUE) %>%
    mutate(value = map(splits, median_as_tibble)) %>%
    int_pctl(value)

  term   .lower    .estimate .upper    .alpha .method
1 median 0.6992978 0.7039473 0.7097946 0.05   percentile

In [ ]:
median_as_tibble <- function(split) {
  dat <- analysis(split)
  tibble(
    term = "median",
    estimate = median(dat$cindex),
    # don't know the analytical std.err so no t-intervals
    std.err = NA_real_
  )
}

bootstrap_median <- function(group) {
    group %>%
    bootstraps(times = 1000, apparent = TRUE) %>%
    mutate(value = map(splits, median_as_tibble)) %>%
    int_pctl(value)
}

In [ ]:
options(digits = 3) 

results %>% 
     select(Group, cindex) %>% 
     group_by(Group) %>%
     group_modify(~ bootstrap_median(.x), .keep = TRUE)

  Group                           term   .lower .estimate .upper .alpha
1 Age >= 65                       median 0.666  0.670     0.673  0.05
2 Annual income < $25k            median 0.708  0.713     0.719  0.05
3 At least one UBR categorization median 0.701  0.706     0.712  0.05
4 Entire population               median 0.699  0.704     0.710  0.05
5 Less than high school education median 0.704  0.710     0.715  0.05
6 No UBR categorization           median 0.684  0.689     0.695  0.05
7 Non-white or Hispanic/Latino    median 0.709  0.713     0.719  0.05
8 Sexual and gender minorities    median 0.701  0.706     0.711  0.05
  .method
1 percentile
2 percentile
3 percentile
4 percentile
5 percentile
6 percentile
7 percentile
8 percentile

In [ ]:
results %>% boot(statistic = function(x,i) median(x %>% select(cindex)),R = 1000)

ERROR: Error in median.default(x %>% select(cindex)): need numeric data

In [ ]:
results %>% 
     select(Group, cindex) %>% 
     group_by(Group) %>%
     group_map(~ boot(cindex, statistic=median,R = 10))
     
     
     # %>% 
     #group_map(~ smean.cl.boot(., conf.int = .95, B = 1000, na.rm = TRUE))# %>%
     #bind_rows()

ERROR: Error in NROW(data): object 'cindex' not found

In [ ]:

    mutate(score = factor(score, levels=scores_plot)) %>%
    mutate(endpoint = factor(endpoint, levels=endpoints_sorted)) %>%
    ungroup() %>%
    pivot_wider(names_from=score, values_from=cindex, id_cols=c(uuid, partition, endpoint, phecode_category, phecode_string, num_events)) %>%
    mutate(id = row_number()) %>%
    rename(score1 = scores_plot[1], score2 = scores_plot[2]) %>%
    mutate(delta=score2 - score1) %>%
    group_by(endpoint, phecode_string, phecode_category) %>%
    median_qi(num_events, delta, score1, score2) %>%
    #mutate(pos = case_when(delta>=0 ~ "pos", delta < 0 ~"neg")) %>%
    mutate(endpoint = fct_reorder(endpoint, delta)) %>%
    mutate(highlight = case_when(endpoint %in% endpoint_selection ~ "YES", TRUE ~ "NO")) %>%# %>% filter(endpoint %in% endpoint_sample)
    mutate(phecode_category = factor(phecode_category, levels=categories_sorted))

temp_num_events

In [ ]:


  stat_dotsinterval(side = "right", scale = 0.5, slab_size = NA) +
  #scale_fill_brewer(palette = "Set3") +
  scale_fill_brewer(palette="Set1") + 
  labs(x="Group", y="C-Index") + 
    theme(axis.title.x=element_blank(),
      panel.grid.major=element_blank(),
      strip.text = element_text(angle=270, hjust=1)
    ) +
    theme(legend.position="none")

In [ ]:

overview = ggplot(temp) +
    geom_ribbon(aes(x=endpoint, ymin=0, ymax=delta), fill="black", alpha=0.2)+
    geom_point(aes(x=endpoint, y=delta, color=highlight, size=highlight, alpha=highlight)) +
    geom_text(data=temp %>% filter(highlight=="YES"), aes(x=endpoint, y=delta+0.1, label="↓"), color="black", size=5, alpha=0.7) +
    #geom_segment(aes(x=endpoint, xend=endpoint, y=0, yend=delta, color=highlight, size=highlight), alpha=0.5)+#+
    labs(x="Endpoints", y="Delta C-Index")+
    scale_color_manual(values=c("NO"="black", "YES"="firebrick"))+
    scale_alpha_manual(values=c("NO"=0.1, "YES"=1))+
    scale_size_manual(values=c("NO"=0.01, "YES"=1))+
    #scale_colour_manual(values = c("pos"="forestgreen", "neg" = "firebrick")) +
    #coord_polar() +
    coord_cartesian(ylim=c(-0.3, 0.3), clip = "off")+
    scale_y_continuous(expand=c(0, 0))+
    scale_x_discrete(expand=expansion(add=20))+
    facet_grid(~phecode_category, scales="free_x", space="free_x")+#, switch=TRUE)+
    #facet_grid2(~phecode_category, scales = "free", independent = "all") +
    theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        panel.grid.major=element_blank(),
         strip.text = element_text(angle=270, hjust=1)) +
    theme(legend.position="none")

    #geom_ribbon(aes(x=id, ymin=AgeSex, ymax=`Age+Sex+MedicalHistory`), fill="red", alpha=0.2)
#geom_violin(size=0.1)
overview

In [ ]:
endpoint_defs = arrow::read_feather(glue("{base_path}/phecode_defs_220306.feather")) %>% arrange(endpoint)
endpoints_md = fread(glue("{base_path}/endpoints.csv"), colClasses=c("phecode"="character"))
endpoints = sort(endpoints_md$endpoint)

glue("{base_path}/phecode_defs_220306.feather")

/sc-projects/sc-proj-ukb-cvd/results/projects/22_medical_records/data/220823_allofus/phecode_defs_220306.feather

In [ ]:
endpoint_map = endpoint_defs$phecode_string
names(endpoint_map) =  endpoint_defs$endpoint
endpoint_order = (endpoint_defs %>% arrange(as.numeric(phecode)))$endpoint

In [ ]:
base_size = 8
title_size = 10
facet_size = 9
geom_text_size=3
theme_set(theme_classic(base_size = base_size) +
          theme(strip.background = element_blank(), plot.title=element_text(size=title_size, hjust=0),
                strip.text.x = element_text(size = facet_size),axis.title=element_text(size=10), axis.text=element_text(size=8, color="black"),
                legend.position="bottom", axis.line = element_line(size = 0.2), axis.ticks=element_line(size=0.2), panel.grid.major.y=element_line()))

In [ ]:
endpoint_selection = c(

   'phecode_401', #  "Hypertension", # intervention
    'phecode_202', #  "Diabetes mellitus", # intervention
    'phecode_416-21', #  "Atrial fibrillation", # intervention
    'phecode_468', #  "Pneumonia", # intervention
    'phecode_474', #  "Chronic obstructive pulmonary disease [COPD]", # interventio
    'phecode_583', #  "Chronic kidney disease", # intervention

    'phecode_404', #  "Ischemic heart disease",
    'phecode_404-1', #  "Myocardial infarction [Heart attack]", # intervention
    'phecode_431-11', #  "Cerebral infarction [Ischemic stroke]",
    'phecode_424', #  "Heart failure", # intervention
    'phecode_420', #  "Cardiac arrest", # intervention
    'OMOP_4306655', #  "All-Cause Death", # intervention

    'phecode_438-11',   #  "Abdominal aortic aneurysm",
    'phecode_440-3',#  "Pulmonary embolism", # intervention
    'phecode_413-21',#  "Aortic stenosis", # intervention
    'phecode_413-11', #  "Mitral valve insufficiency",
    'phecode_410-2',#  "Endocarditis",
    'phecode_400',#  "Rheumatic fever and chronic rheumatic heart diseases",

    'phecode_164', #  "Anemia", # intervention
    'phecode_718',  #  "Back pain", # intervention
    'phecode_324-11', #  "Parkinson's disease (Primary)",
    'phecode_705-1', #  "Rheumatoid arthritis", # NEW + interventio
    'phecode_665', #  "Psoriasis", # interesting
    'phecode_284'#  "Suicide ideation and attempt or self harm" # intervention
)
endpoint_defs = endpoint_defs %>%
    mutate(name = phecode_string) %>%
    mutate(name =
           case_when(
               phecode_string == "Myocardial infarction [Heart attack]"~"Myocardial infarction",
               phecode_string == "Cerebral infarction [Ischemic stroke]"~"Ischemic stroke",
               phecode_string == "Chronic obstructive pulmonary disease [COPD]"~"COPD",
               phecode_string == "Mitral valve insufficiency"~"Mitral insufficiency",
               phecode_string == "Parkinson's disease (Primary)"~"Parkinson's",
               phecode_string == "Suicide ideation and attempt or self harm"~"Suicide attempt",
               phecode_string == "Ischemic heart disease"~"Ischemic HD",
               phecode_string == "Chronic kidney disease"~"Chronic KD",
               phecode_string == "Rheumatic fever and chronic rheumatic heart diseases"~"Rheumatic HD",
               phecode_string == "Abdominal aortic aneurysm"~"Abdominal AA",
                  TRUE ~ name)
           )

endpoint_map = endpoint_defs$name
names(endpoint_map) =  endpoint_defs$endpoint
#endpoint_order = (endpoint_defs %>% arrange(as.numeric(phecode)))$endpoint
endpoint_order = endpoint_selection

In [ ]:
name = "220831_bootstrap_results"
benchmark_endpoints = arrow::read_feather(glue("{base_path}/{name}.feather"))

In [ ]:
benchmark_endpoints = benchmark_endpoints %>% group_by(endpoint, uuid) %>% filter(all(!is.na(cindex))) %>% ungroup()

In [ ]:
benchmark_endpoints = setDT(benchmark_endpoints)[, endpoint := str_replace(endpoint, "\\.", "-")] %>% as_tibble()

In [ ]:
benchmark_endpoints = benchmark_endpoints %>% left_join(endpoints_md)

Joining, by = "endpoint"

In [ ]:
benchmark_endpoints %>% select(phecode_string) %>% filter(is.na(phecode_string))

     phecode_string

In [ ]:
benchmark_endpoints %>% group_by(endpoint, score)  %>% summarise(cindex=mean(cindex)) %>% group_by(score) %>% summarise(mean(cindex)) %>% arrange(`mean(cindex)`)

`summarise()` has grouped output by 'endpoint'. You can override using the
`.groups` argument.

  score                            mean(cindex)
1 AgeSex_AoUCPH                    0.6318432
2 AgeSex+MedicalHistory_UKBBParams 0.7094673
3 AgeSex+MedicalHistory_AoUCPH     0.7332246

In [ ]:
endpoints_sorted = (benchmark_endpoints %>%
    filter(score == "AgeSex+MedicalHistory_UKBBParams") %>%
    group_by(endpoint, score) %>%
    summarise(cindex=mean(cindex, na.rm=TRUE)) %>%
    arrange(cindex) %>% ungroup())$endpoint

`summarise()` has grouped output by 'endpoint'. You can override using the
`.groups` argument.

In [ ]:
categories_sorted = (endpoint_defs %>% distinct(phecode_category))$phecode_category

In [ ]:
temp_num_events = benchmark_endpoints %>%
    filter(score %in% scores_plot) %>%
    mutate(score = factor(score, levels=scores_plot)) %>%
    mutate(endpoint = factor(endpoint, levels=endpoints_sorted)) %>%
    ungroup() %>%
    pivot_wider(names_from=score, values_from=cindex, id_cols=c(uuid, partition, endpoint, phecode_category, phecode_string, num_events)) %>%
    mutate(id = row_number()) %>%
    rename(score1 = scores_plot[1], score2 = scores_plot[2]) %>%
    mutate(delta=score2 - score1) %>%
    group_by(endpoint, phecode_string, phecode_category) %>%
    median_qi(num_events, delta, score1, score2) %>%
    #mutate(pos = case_when(delta>=0 ~ "pos", delta < 0 ~"neg")) %>%
    mutate(endpoint = fct_reorder(endpoint, delta)) %>%
    mutate(highlight = case_when(endpoint %in% endpoint_selection ~ "YES", TRUE ~ "NO")) %>%# %>% filter(endpoint %in% endpoint_sample)
    mutate(phecode_category = factor(phecode_category, levels=categories_sorted))

temp_num_events

     endpoint
1    phecode_441-1
2    phecode_168-21
3    phecode_209-22
4    phecode_084-2
5    phecode_168-2
6    phecode_110-4
7    phecode_209-2
8    phecode_174-1
9    phecode_979
10   phecode_054-2
11   phecode_978
12   phecode_540-2
13   phecode_540-1
14   phecode_589
15   phecode_355-21
16   phecode_069
17   phecode_283-8
18   phecode_124-7
19   phecode_540-3
20   phecode_719-3
21   phecode_054
22   phecode_168-3
23   phecode_012
24   phecode_098
25   phecode_004
26   phecode_149-4
27   phecode_052-31
28   phecode_343-5
29   phecode_724
30   phecode_809
⋮    ⋮
1719 phecode_688-6
1720 phecode_208-22
1721 phecode_444-13
1722 phecode_374-42
1723 phecode_413-6
1724 phecode_583-1
1725 phecode_374-512
1726 phecode_328-1
1727 phecode_168-12
1728 phecode_586-5
1729 phecode_328-7
1730 phecode_337-8
1731 phecode_419-2
1732 phecode_103-3
1733 phecode_419
1734 phecode_249-1
1735 phecode_328-2
1736 phecode_416-3
1737 phecode_542-5
1738 phecode_608-1
1739 phecode_205-3
1740 phecode_209-23
1741 phecode_414-5
1742 phecode_416-213
1743 phecode_416-212
1744 phecode_416-222
1745 phecode_584-1
1746 phecode_979-2
1747 phecode_328-4
1748 phecode_416-214
     phecode_string
1    Arteriovenous fistula
2    Primary hypercoagulable state [Primary thrombophilia]
3    Hypopituitarism NOS
4    Malaria [Plasmodium]
5    Hyper-coagulability
6    Malignant neoplasm of the pituitary gland and craniopharyngeal duct
7    Hypopituitarism
8    Hyposplenism*
9    Transplated organ
10   Hepatitis B
11   Tissue transplant or graft
12   Acute hepatitis
13   Chronic hepatitis
14   Pathological lesions of kidney
15   Transient alteration of awareness
16   Other specified viral infections
17   Other problems related to lifestyle
18   Chronic myeloproliferative disease
19   Viral hepatitits
20   Separation of muscle (nontraumatic)
21   Hepatovirus
22   Hereditary deficiency of other clotting factors
23   Proteus
24   Carrier or suspected carrier of infectious diseases
25   Streptococcus
26   Benign neoplasm of the pituitary gland and craniopharyngeal duct
27   Varicella [chickenpox]
28   Horner's syndrome*
29   Other symptoms and disorders of the soft tissue
30   Pain
⋮    ⋮
1719 Rheumatoid nodule*
1720 Secondary hyperparathyroidism
1721 Esophageal varix
1722 Diabetic retinopathy
1723 Heart valve replaced
1724 End stage renal disease [CDK, stage 5]
1725 Exuadative (wet) age-related macular degeneration
1726 Alzheimer's disease
1727 Hemorrhagic disorder due to intrinsic circulating anticoagulants
1728 Renal sclerosis, unspecified
1729 Vascular dementia
1730 Polyneuropathy in diseases classified elsewhere
1731 Presence of cardiac defibrillator
1732 Carcinoma in situ of skin
1733 Presence of cardiac device
1734 Cerebral amyloid angiopathy*
1735 Frontotemporal dementia
1736 Ventricular fibrillation and flutter
1737 Hepatorenal syndrome
1738 Abnormal findings in semen
1739 Drug-induced hypoglycemia*
1740 Iatrogenic hypopituitarism*
1741 Ischemic cardiomyopathy*
1742 Chronic atrial fibrillation*
1743 Persistent atrial fibrillation*
1744 Atypical atrial flutter*
1745 Renal dialysis
1746 Kidney transplant
1747 Dementia with Lewy bodies
1748 Permanent atrial fibrillation*
     phecode_category num_events num_events.lower num_events.upper delta
1    Cardio             245.0      216.475          276.525        -0.486594891
2    Blood              861.0      808.475          926.050        -0.262660996
3    Endo               149.0      127.000          168.000        -0.329952095
4    ID                   4.0        1.000            8.000        -0.442494079
5    Blood              952.0      888.950         1015.575        -0.249456515
6    Neoplasms           41.0       29.000           56.050        -0.266717171
7    Endo               180.0      157.000          205.525        -0.250280463
8    Blood                3.0        1.000            6.800        -0.606466499
9    Stat               824.0      765.950          880.050        -0.397117471
10   ID                 342.0      308.475          376.525        -0.247252793
11   Stat               291.0      258.000          327.525        -0.303059331
12   GI                 661.0      616.475          715.000        -0.225940888
13   GI                1434.5     1362.425         1509.525        -0.300760953
14   Genitourinary       99.0       80.475          117.000        -0.230617223
15   Neuro                1.0        1.000            3.600        -0.435748645
16   ID                  30.0       20.000           40.000        -0.176110234
17   Mental            1552.0     1481.950         1636.050        -0.136421720
18   Neoplasms          363.0      329.475          400.525        -0.294230747
19   GI                1508.5     1439.000         1585.525        -0.274172625
20   Musc/Skel           11.0        5.000           17.000        -0.156689342
21   ID                1508.5     1439.000         1585.525        -0.272915372
22   Blood                6.0        2.000           11.000        -0.343026678
23   ID                   1.0        1.000            4.000        -0.447868870
24   ID                 750.0      700.900          807.525        -0.198594835
25   ID                3668.5     3553.950         3802.100        -0.194731085
26   Neoplasms          232.0      204.000          260.050        -0.105187110
27   ID                 180.0      155.000          209.525        -0.056512044
28   Neuro                2.0        1.000            5.000        -0.480255413
29   Musc/Skel        18198.0    17972.900        18448.350         0.007867683
30   Signs/Symptoms   19119.0    18847.175        19366.100        -0.004055798
⋮    ⋮                ⋮          ⋮                ⋮                ⋮
1719 Derm               23.0       15.000           33.000          0.225854293
1720 Endo             1217.0     1151.800         1285.525          0.236612170
1721 Cardio            352.0      317.475          386.575          0.242531373
1722 Eye               971.0      899.850         1027.050          0.254578081
1723 Cardio            699.0      653.950          744.525          0.129893134
1724 Genitourinary     929.0      868.950          986.000          0.251375509
1725 Eye               176.0      153.475          205.000         -0.005851253
1726 Neuro             306.5      274.475          341.525          0.010711797
1727 Blood             255.0      223.475          288.000          0.158054007
1728 Genitourinary     398.0      364.000          433.575          0.275702638
1729 Neuro             259.0      226.425          288.525          0.055173451
1730 Neuro            2537.5     2453.325         2637.050          0.232086027
1731 Cardio             91.5       73.475          110.525          0.196157569
1732 Neoplasms         594.5      549.000          643.525          0.050241073
1733 Cardio            203.0      181.475          231.000          0.140342310
1734 Metab              29.0       18.000           39.000          0.019015332
1735 Neuro              37.0       25.475           50.050          0.057624779
1736 Cardio            219.0      188.950          245.000          0.208042258
1737 GI                 95.0       78.475          115.000          0.275083244
1738 Genitourinary    1383.0     1309.475         1458.100          0.003220062
1739 Endo               68.0       52.000           86.050          0.288278244
1740 Endo               14.0        8.000           22.000          0.288409589
1741 Cardio            838.0      781.425          895.000          0.141548658
1742 Cardio            926.0      865.950          998.625          0.107849300
1743 Cardio           1133.5     1065.900         1192.000          0.088258289
1744 Cardio            223.0      196.475          253.525          0.122106563
1745 Genitourinary      54.0       42.475           69.000          0.357421427
1746 Stat              325.0      290.000          361.525          0.334243299
1747 Neuro              46.0       35.000           61.000          0.051628039
1748 Cardio            357.5      320.000          399.525          0.086468321
     delta.lower  delta.upper   score1    score1.lower score1.upper score2
1    -0.551437407  0.3539902858 0.5938846 0.5631923    0.6222280    0.1027433
2    -0.294607645 -0.1240949425 0.5451966 0.5267965    0.5620531    0.2807817
3    -0.394441043  0.1727290262 0.6002899 0.5517462    0.6435207    0.2682035
4    -0.815852612 -0.2483819302 0.7676631 0.4548741    0.9981319    0.3114163
5    -0.284687262  0.1978014208 0.5424204 0.5261798    0.5608187    0.2933224
6    -0.428702066  0.2210712267 0.5676405 0.5126722    0.6520001    0.2912333
7    -0.332260678  0.1205680975 0.5840633 0.5450221    0.6219725    0.3300814
8    -0.914215070  0.2477878854 0.8058470 0.6752929    0.9318945    0.1759767
9    -0.454792122  0.1961590202 0.6090362 0.5936856    0.6294526    0.2120589
10   -0.315766984  0.1122195665 0.5806127 0.5510573    0.6089848    0.3287572
11   -0.389098646  0.1105247830 0.6401674 0.6115217    0.6679248    0.3311119
12   -0.272968240  0.1389156567 0.5656112 0.5475246    0.5841950    0.3394604
13   -0.337423783  0.0849380385 0.6197728 0.6058164    0.6333573    0.3168820
14   -0.401739110  0.2541217571 0.5700158 0.5193490    0.6228209    0.3361262
15   -0.462293710 -0.4179966985 0.8504492 0.8491427    0.8517211    0.4142551
16   -0.306051993 -0.0652080909 0.5940292 0.5188590    0.6980608    0.4188262
17   -0.156865281 -0.1113566855 0.5666748 0.5527375    0.5797658    0.4301124
18   -0.391726223  0.0104965980 0.6938945 0.6673830    0.7190414    0.3941591
19   -0.307325244  0.0782069477 0.6176180 0.6038356    0.6307844    0.3439686
20   -0.508709978  0.0661235137 0.6033051 0.5000647    0.7851031    0.4371137
21   -0.306930054  0.0783951347 0.6176180 0.6038356    0.6307844    0.3449091
22   -0.666776871 -0.1208185578 0.8038876 0.6716027    0.9848868    0.4530657
23   -0.457738357 -0.4290857238 0.9232325 0.9220584    0.9243751    0.4754944
24   -0.243577520 -0.1597688026 0.6782403 0.6591706    0.6987934    0.4812759
25   -0.215769698 -0.1745697846 0.6784545 0.6694772    0.6882850    0.4842333
26   -0.214223918  0.0782954968 0.5623422 0.5301446    0.5957413    0.4519184
27   -0.112334060  0.0004559116 0.5655678 0.5256759    0.6058598    0.5099860
28   -0.656401388 -0.2995675347 0.9914127 0.9880245    0.9945076    0.5119524
29    0.002008288  0.0131185270 0.5109924 0.5065143    0.5152120    0.5189312
30   -0.011067881  0.0018947567 0.5245763 0.5202786    0.5290675    0.5205523
⋮    ⋮            ⋮             ⋮         ⋮            ⋮            ⋮
1719  0.109211260 0.345155452   0.6512068 0.5527729    0.7356174    0.8766790
1720  0.221492568 0.251650904   0.6375121 0.6231374    0.6511516    0.8745744
1721  0.207438024 0.270190424   0.6324639 0.6106516    0.6560632    0.8750821
1722  0.233538329 0.279206417   0.6219465 0.6066561    0.6381999    0.8773779
1723  0.112257398 0.150598147   0.7470615 0.7285384    0.7636214    0.8772123
1724  0.235817385 0.272019575   0.6263757 0.6076332    0.6424463    0.8783179
1725 -0.027774092 0.017162640   0.8839449 0.8650131    0.9016578    0.8785068
1726  0.002307917 0.019078121   0.8683726 0.8524171    0.8818249    0.8800492
1727  0.127853008 0.191335058   0.7223049 0.6912123    0.7522555    0.8805552
1728  0.244453847 0.306015309   0.6044041 0.5787944    0.6289079    0.8803996
1729  0.041827296 0.067450626   0.8257690 0.8053640    0.8453786    0.8806698
1730  0.221714684 0.242423918   0.6499486 0.6416973    0.6578315    0.8820522
1731  0.128203969 0.261125911   0.6877203 0.6396524    0.7441870    0.8821816
1732  0.039963637 0.060705008   0.8337703 0.8174773    0.8460415    0.8835675
1733  0.110655441 0.173546367   0.7442965 0.7107584    0.7770210    0.8846063
1734 -0.023081976 0.057800181   0.8665411 0.8149408    0.9081574    0.8878681
1735  0.001353454 0.107581219   0.8326222 0.7763700    0.8822622    0.8883923
1736  0.170109711 0.246817423   0.6826627 0.6536639    0.7163393    0.8921007
1737  0.223841033 0.336039266   0.6143197 0.5626603    0.6611522    0.8938799
1738 -0.001716991 0.007347175   0.8917933 0.8857585    0.8973531    0.8947688
1739  0.227131903 0.341782979   0.6069395 0.5617450    0.6652290    0.8953690
1740  0.104657383 0.443746587   0.6153704 0.5119475    0.7504984    0.9053117
1741  0.123139341 0.156339565   0.7641381 0.7482989    0.7774358    0.9045919
1742  0.097706645 0.121266268   0.7966403 0.7862079    0.8097523    0.9051469
1743  0.076943654 0.100764530   0.8229753 0.8136391    0.8324520    0.9117763
1744  0.094432895 0.152863219   0.7889239 0.7642945    0.8121490    0.9113288
1745 -0.315117042 0.443843710   0.6092560 0.5296179    0.6752775    0.9725287
1746  0.303311612 0.364822576   0.5813840 0.5515427    0.6096162    0.9165790
1747  0.014535734 0.087203405   0.8794644 0.8393135    0.9121490    0.9302850
1748  0.068625739 0.104524563   0.8513196 0.8333051    0.8647854    0.9381364
     score2.lower score2.upper .width .point .interval highlight
1    0.057324984  0.9419017    0.95   median qi        NO
2    0.258583505  0.4202165    0.95   median qi        NO
3    0.217505531  0.7715150    0.95   median qi        NO
4    0.178110526  0.4271489    0.95   median qi        NO
5    0.262727506  0.7351103    0.95   median qi        NO
6    0.190010823  0.7874490    0.95   median qi        NO
7    0.277091590  0.7124547    0.95   median qi        NO
8    0.004581364  0.9961194    0.95   median qi        NO
9    0.166115756  0.7995448    0.95   median qi        NO
10   0.280441298  0.6960634    0.95   median qi        NO
11   0.253298052  0.7521747    0.95   median qi        NO
12   0.297204466  0.7015688    0.95   median qi        NO
13   0.286925834  0.7004987    0.95   median qi        NO
14   0.185345747  0.8153153    0.95   median qi        NO
15   0.387873046  0.4321083    0.95   median qi        NO
16   0.314777498  0.5367642    0.95   median qi        NO
17   0.417833601  0.4488211    0.95   median qi        NO
18   0.301005104  0.7087640    0.95   median qi        NO
19   0.312776432  0.6958516    0.95   median qi        NO
20   0.255115951  0.6640712    0.95   median qi        NO
21   0.313257966  0.6960634    0.95   median qi        NO
22   0.172728296  0.7665032    0.95   median qi        NO
23   0.465365252  0.4940693    0.95   median qi        NO
24   0.452906973  0.5016766    0.95   median qi        NO
25   0.468166966  0.4993428    0.95   median qi        NO
26   0.370625557  0.6337418    0.95   median qi        NO
27   0.466862254  0.5533276    0.95   median qi        NO
28   0.338014971  0.6888087    0.95   median qi        NO
29   0.514463723  0.5239963    0.95   median qi        NO
30   0.516190461  0.5250044    0.95   median qi        NO
⋮    ⋮            ⋮            ⋮      ⋮      ⋮         ⋮
1719 0.7924899    0.9413540    0.95   median qi        NO
1720 0.8618293    0.8853360    0.95   median qi        NO
1721 0.8563862    0.8915663    0.95   median qi        NO
1722 0.8630834    0.8902072    0.95   median qi        NO
1723 0.8639988    0.8897911    0.95   median qi        NO
1724 0.8661536    0.8891853    0.95   median qi        NO
1725 0.8540903    0.9026447    0.95   median qi        NO
1726 0.8625777    0.8927625    0.95   median qi        NO
1727 0.8614712    0.8961252    0.95   median qi        NO
1728 0.8646898    0.8984112    0.95   median qi        NO
1729 0.8623186    0.8958798    0.95   median qi        NO
1730 0.8747498    0.8887812    0.95   median qi        NO
1731 0.8349583    0.9222456    0.95   median qi        NO
1732 0.8736159    0.8943396    0.95   median qi        NO
1733 0.8653592    0.9050638    0.95   median qi        NO
1734 0.8431124    0.9229058    0.95   median qi        NO
1735 0.8430257    0.9282419    0.95   median qi        NO
1736 0.8657341    0.9124598    0.95   median qi        NO
1737 0.8596931    0.9291426    0.95   median qi        NO
1738 0.8899574    0.8989999    0.95   median qi        NO
1739 0.8628101    0.9313703    0.95   median qi        NO
1740 0.7905899    0.9966425    0.95   median qi        NO
1741 0.8944947    0.9146719    0.95   median qi        NO
1742 0.8969677    0.9138689    0.95   median qi        NO
1743 0.9016656    0.9196621    0.95   median qi        NO
1744 0.8945619    0.9282919    0.95   median qi        NO
1745 0.3013534    0.9897679    0.95   median qi        NO
1746 0.8937866    0.9346499    0.95   median qi        NO
1747 0.9001100    0.9539716    0.95   median qi        NO
1748 0.9273236    0.9474495    0.95   median qi        NO

In [ ]:
temp_num_events %>% filter(delta.upper < 0)

   endpoint
1  phecode_168-21
2  phecode_084-2
3  phecode_355-21
4  phecode_069
5  phecode_283-8
6  phecode_168-3
7  phecode_012
8  phecode_098
9  phecode_004
10 phecode_343-5
11 phecode_299
12 phecode_232-1
13 phecode_339-1
14 phecode_280-8
15 phecode_339
16 phecode_280
17 phecode_229
18 phecode_826-4
19 phecode_418
20 phecode_280-82
21 phecode_281
22 phecode_230-1
23 phecode_500-4
24 phecode_281-2
25 phecode_104-3
26 phecode_104
27 phecode_823
28 phecode_112
29 phecode_674-23
30 phecode_680-2
⋮  ⋮
42 phecode_239-3
43 phecode_165-2
44 phecode_165-3
45 phecode_664-2
46 phecode_323-31
47 phecode_088
48 phecode_664-21
49 phecode_466-3
50 phecode_835
51 phecode_281-1
52 phecode_599-7
53 phecode_329-9
54 phecode_293-1
55 phecode_280-81
56 phecode_507-3
57 phecode_370-3
58 phecode_142-1
59 phecode_084-4
60 phecode_672
61 phecode_614-55
62 phecode_142
63 phecode_466-1
64 phecode_362-6
65 phecode_581-3
66 phecode_684-2
67 phecode_597
68 phecode_105
69 phecode_726-1
70 phecode_822-8
71 phecode_822
   phecode_string
1  Primary hypercoagulable state [Primary thrombophilia]
2  Malaria [Plasmodium]
3  Transient alteration of awareness
4  Other specified viral infections
5  Other problems related to lifestyle
6  Hereditary deficiency of other clotting factors
7  Proteus
8  Carrier or suspected carrier of infectious diseases
9  Streptococcus
10 Horner's syndrome*
11 Mental disorder, not otherwise specified
12 Vitamin A deficiency
13 Muscular dystrophy
14 Other psychoactive substance related disorders
15 Primary disorders of muscles
16 Substance related disorders
17 Other endocrine disorders
18 Other and unspecified nonspecific immunological findings
19 Abnormal results of cardiovascular function studies
20 Other psychoactive substance dependence
21 Substance abuse, dependence, and withdrawl
22 Protein-calorie malnutrition
23 Disturbances in tooth eruption
24 Substance dependence
25 Malignant neoplasm of other connective and soft tissue
26 Malignant sarcoma-related cancers
27 Abnormal serum enzyme levels
28 Malignant neoplasm of other and ill-defined sites
29 Acanthosis nigricans
30 Keratoderma
⋮  ⋮
42 Mixed hyperlipidemia
43 Thalassemia
44 Hemoglobin C trait [Sickle-cell trait]
45 Pityriasis
46 Amyotrophic lateral sclerosis [ALS]
47 Sexually transmitted disease
48 Pityriasis rosea
49 Peritonsillar abscess
50 Cytology and pathology findings
51 Substance abuse
52 Urethral discharge
53 Delirium
54 Anorexia nervosa
55 Other psychoactive substance abuse
56 Oral leukoplakia
57 Vascular disorders of iris and ciliary body
58 Lump or mass in breast
59 Trichomoniasis
60 Other acute skin changes due to ultraviolet radiation
61 Candidiasis of vulva and vagina
62 Lump or mass in breast or nonspecific abnormal breast exam
63 Acute tonsillitis and adenoiditis
64 Dermatochalasis of eyelid
65 Obstructive and reflux uropathy
66 Hypertrichosis and hirsutism
67 Other disorders of urethra and urinary tract
68 Malignant neoplasm of the breast
69 Osteoporosis
70 Abnormal tumor markers
71 Other and nonspecific abnormal cytological, histological and immunological findings
   phecode_category num_events num_events.lower num_events.upper delta
1  Blood              861.0      808.475          926.050        -0.26266100
2  ID                   4.0        1.000            8.000        -0.44249408
3  Neuro                1.0        1.000            3.600        -0.43574864
4  ID                  30.0       20.000           40.000        -0.17611023
5  Mental            1552.0     1481.950         1636.050        -0.13642172
6  Blood                6.0        2.000           11.000        -0.34302668
7  ID                   1.0        1.000            4.000        -0.44786887
8  ID                 750.0      700.900          807.525        -0.19859484
9  ID                3668.5     3553.950         3802.100        -0.19473109
10 Neuro                2.0        1.000            5.000        -0.48025541
11 Mental           18197.5    17913.450        18401.675        -0.01991253
12 Metab              116.5       95.475          138.525        -0.10740953
13 Neuro              104.0       82.475          123.525        -0.13077882
14 Mental            9325.0     9143.425         9508.025        -0.07060255
15 Neuro              126.0      106.000          148.000        -0.10193180
16 Mental           10530.5    10339.475        10708.675        -0.06076739
17 Endo             14634.0    14436.700        14843.625        -0.01389687
18 Signs/Symptoms     219.0      192.475          250.000        -0.07195213
19 Cardio           17436.0    17228.950        17668.825        -0.02054916
20 Mental            9148.5     8994.425         9326.575        -0.05118967
21 Mental            9858.0     9673.325        10030.550        -0.04648847
22 Metab            14361.0    14161.225        14598.525        -0.01101969
23 GI                 222.5      188.950          253.525        -0.16729585
24 Mental            9542.0     9372.700         9718.100        -0.02545846
25 Neoplasms         6594.0     6459.000         6774.625        -0.02335969
26 Neoplasms         6705.5     6565.750         6896.675        -0.02384672
27 Signs/Symptoms    7023.5     6861.600         7166.625        -0.03651989
28 Neoplasms        15102.0    14882.025        15364.500        -0.01247891
29 Derm               219.0      191.475          250.100        -0.10351747
30 Derm              5481.5     5352.475         5647.825        -0.09588378
⋮  ⋮                ⋮          ⋮                ⋮                ⋮
42 Metab            7552.5     7395.425         7723.625         -0.04861935
43 Blood             180.0      155.950          210.525         -0.06194290
44 Blood             214.5      187.475          244.525         -0.08164433
45 Derm              136.0      114.475          161.050         -0.09471084
46 Neuro              38.0       26.000           49.000         -0.12980393
47 ID               2430.5     2350.950         2531.575         -0.02594675
48 Derm              109.5       88.950          130.000         -0.08295840
49 Resp              107.0       88.475          126.000         -0.09960326
50 Signs/Symptoms   3094.0     2983.950         3196.150         -0.03729733
51 Mental           5085.5     4942.475         5216.525         -0.02579956
52 Genitourinary     198.0      172.425          218.525         -0.21323363
53 Neuro             177.5      155.475          206.525         -0.05720890
54 Mental             71.5       55.475           90.525         -0.14024916
55 Mental           4883.0     4732.800         5001.575         -0.01804747
56 GI                307.0      278.000          344.525         -0.05751802
57 Eye                10.0        5.000           17.000         -0.14960856
58 Neoplasms        4607.0     4481.475         4744.200         -0.03225076
59 ID                477.0      435.475          517.575         -0.10729682
60 Derm             3391.0     3276.950         3514.625         -0.02215247
61 Genitourinary     160.0      136.950          188.000         -0.11036084
62 Neoplasms        6069.0     5888.900         6207.575         -0.03418719
63 Resp              744.5      695.475          800.000         -0.03334672
64 Eye               693.0      639.000          750.625         -0.06842226
65 Genitourinary    4427.0     4306.425         4547.100         -0.02097248
66 Derm              424.0      387.475          461.050         -0.04440379
67 Genitourinary    3580.0     3463.950         3712.000         -0.07462041
68 Neoplasms        1488.0     1415.000         1565.050         -0.01258417
69 Musc/Skel        4071.0     3952.900         4185.525         -0.01180612
70 Signs/Symptoms   1421.0     1348.950         1504.000         -0.05857387
71 Signs/Symptoms   1421.0     1348.950         1504.000         -0.05856452
   delta.lower delta.upper  .width .point .interval highlight
1  -0.29460764 -0.124094943 0.95   median qi        NO
2  -0.81585261 -0.248381930 0.95   median qi        NO
3  -0.46229371 -0.417996699 0.95   median qi        NO
4  -0.30605199 -0.065208091 0.95   median qi        NO
5  -0.15686528 -0.111356686 0.95   median qi        NO
6  -0.66677687 -0.120818558 0.95   median qi        NO
7  -0.45773836 -0.429085724 0.95   median qi        NO
8  -0.24357752 -0.159768803 0.95   median qi        NO
9  -0.21576970 -0.174569785 0.95   median qi        NO
10 -0.65640139 -0.299567535 0.95   median qi        NO
11 -0.02949031 -0.010250917 0.95   median qi        NO
12 -0.18075106 -0.037698060 0.95   median qi        NO
13 -0.27942719 -0.050778798 0.95   median qi        NO
14 -0.08096298 -0.058186692 0.95   median qi        NO
15 -0.15993997 -0.029562901 0.95   median qi        NO
16 -0.06944642 -0.049201574 0.95   median qi        NO
17 -0.02087287 -0.007466382 0.95   median qi        NO
18 -0.13229318 -0.020465367 0.95   median qi        NO
19 -0.02561956 -0.016201046 0.95   median qi        NO
20 -0.06247777 -0.039818511 0.95   median qi        NO
21 -0.05534109 -0.038314808 0.95   median qi        NO
22 -0.01726355 -0.004643799 0.95   median qi        NO
23 -0.24045907 -0.097090333 0.95   median qi        NO
24 -0.03530850 -0.017647395 0.95   median qi        NO
25 -0.03296229 -0.011096833 0.95   median qi        NO
26 -0.03093037 -0.014779919 0.95   median qi        NO
27 -0.04542195 -0.026240038 0.95   median qi        NO
28 -0.01623643 -0.008284632 0.95   median qi        NO
29 -0.17361862 -0.031805853 0.95   median qi        NO
30 -0.11464424 -0.076356788 0.95   median qi        NO
⋮  ⋮           ⋮            ⋮      ⋮      ⋮         ⋮
42 -0.06597282 -0.032987041 0.95   median qi        NO
43 -0.11318143 -0.001771492 0.95   median qi        NO
44 -0.13888298 -0.037764794 0.95   median qi        NO
45 -0.16531332 -0.009355498 0.95   median qi        NO
46 -0.21947987 -0.053272361 0.95   median qi        NO
47 -0.04442006 -0.004294096 0.95   median qi        NO
48 -0.15834422 -0.008976344 0.95   median qi        NO
49 -0.16940423 -0.039923680 0.95   median qi        NO
50 -0.04970515 -0.024896929 0.95   median qi        NO
51 -0.03807620 -0.012593512 0.95   median qi        NO
52 -0.26885794 -0.154680387 0.95   median qi        NO
53 -0.11574261 -0.006835202 0.95   median qi        NO
54 -0.23640111 -0.043389600 0.95   median qi        NO
55 -0.03110348 -0.003273351 0.95   median qi        NO
56 -0.09280650 -0.018391372 0.95   median qi        NO
57 -0.22358877 -0.080927647 0.95   median qi        NO
58 -0.04034957 -0.024072577 0.95   median qi        NO
59 -0.14244655 -0.068196370 0.95   median qi        NO
60 -0.04129195 -0.002261664 0.95   median qi        NO
61 -0.14889737 -0.068595880 0.95   median qi        NO
62 -0.04134876 -0.026070447 0.95   median qi        NO
63 -0.05884122 -0.012363493 0.95   median qi        NO
64 -0.09922170 -0.039416842 0.95   median qi        NO
65 -0.03046287 -0.010672992 0.95   median qi        NO
66 -0.08674701 -0.012361187 0.95   median qi        NO
67 -0.09405498 -0.058720627 0.95   median qi        NO
68 -0.02518279 -0.002337119 0.95   median qi        NO
69 -0.01787767 -0.004497135 0.95   median qi        NO
70 -0.07254456 -0.045608019 0.95   median qi        NO
71 -0.07253376 -0.045611863 0.95   median qi        NO

In [ ]:
plot_width = 8.25; plot_height=2.5; plot_res = 320
options(repr.plot.width = plot_width, repr.plot.height = plot_height, repr.plot.res=plot_res)

library(ggtext)
library(ggdist)

scores_plot = c("AgeSex_AoUCPH", "AgeSex+MedicalHistory_UKBBParams")

temp = benchmark_endpoints %>%
    filter(score %in% scores_plot) %>%
    mutate(score = factor(score, levels=scores_plot)) %>%
    mutate(endpoint = factor(endpoint, levels=endpoints_sorted)) %>%
    ungroup() %>%
    pivot_wider(names_from=score, values_from=cindex, id_cols=c(uuid, partition, endpoint, phecode_category, phecode_string, num_events)) %>%
    mutate(id = row_number()) %>%
    rename(score1 = scores_plot[1], score2 = scores_plot[2]) %>%
    mutate(delta=score2 - score1) %>%
    group_by(endpoint, phecode_string, phecode_category) %>%
    median_qi(delta) %>%
    #mutate(pos = case_when(delta>=0 ~ "pos", delta < 0 ~"neg")) %>%
    mutate(endpoint = fct_reorder(endpoint, delta)) %>%
    mutate(highlight = case_when(endpoint %in% endpoint_selection ~ "YES", TRUE ~ "NO")) %>%# %>% filter(endpoint %in% endpoint_sample)
    mutate(phecode_category = factor(phecode_category, levels=categories_sorted))

In [ ]:
temp

     endpoint
1    phecode_441-1
2    phecode_168-21
3    phecode_209-22
4    phecode_084-2
5    phecode_168-2
6    phecode_110-4
7    phecode_209-2
8    phecode_174-1
9    phecode_979
10   phecode_054-2
11   phecode_978
12   phecode_540-2
13   phecode_540-1
14   phecode_589
15   phecode_355-21
16   phecode_069
17   phecode_283-8
18   phecode_124-7
19   phecode_540-3
20   phecode_719-3
21   phecode_054
22   phecode_168-3
23   phecode_012
24   phecode_098
25   phecode_004
26   phecode_149-4
27   phecode_052-31
28   phecode_343-5
29   phecode_724
30   phecode_809
⋮    ⋮
1719 phecode_688-6
1720 phecode_208-22
1721 phecode_444-13
1722 phecode_374-42
1723 phecode_413-6
1724 phecode_583-1
1725 phecode_374-512
1726 phecode_328-1
1727 phecode_168-12
1728 phecode_586-5
1729 phecode_328-7
1730 phecode_337-8
1731 phecode_419-2
1732 phecode_103-3
1733 phecode_419
1734 phecode_249-1
1735 phecode_328-2
1736 phecode_416-3
1737 phecode_542-5
1738 phecode_608-1
1739 phecode_205-3
1740 phecode_209-23
1741 phecode_414-5
1742 phecode_416-213
1743 phecode_416-212
1744 phecode_416-222
1745 phecode_584-1
1746 phecode_979-2
1747 phecode_328-4
1748 phecode_416-214
     phecode_string
1    Arteriovenous fistula
2    Primary hypercoagulable state [Primary thrombophilia]
3    Hypopituitarism NOS
4    Malaria [Plasmodium]
5    Hyper-coagulability
6    Malignant neoplasm of the pituitary gland and craniopharyngeal duct
7    Hypopituitarism
8    Hyposplenism*
9    Transplated organ
10   Hepatitis B
11   Tissue transplant or graft
12   Acute hepatitis
13   Chronic hepatitis
14   Pathological lesions of kidney
15   Transient alteration of awareness
16   Other specified viral infections
17   Other problems related to lifestyle
18   Chronic myeloproliferative disease
19   Viral hepatitits
20   Separation of muscle (nontraumatic)
21   Hepatovirus
22   Hereditary deficiency of other clotting factors
23   Proteus
24   Carrier or suspected carrier of infectious diseases
25   Streptococcus
26   Benign neoplasm of the pituitary gland and craniopharyngeal duct
27   Varicella [chickenpox]
28   Horner's syndrome*
29   Other symptoms and disorders of the soft tissue
30   Pain
⋮    ⋮
1719 Rheumatoid nodule*
1720 Secondary hyperparathyroidism
1721 Esophageal varix
1722 Diabetic retinopathy
1723 Heart valve replaced
1724 End stage renal disease [CDK, stage 5]
1725 Exuadative (wet) age-related macular degeneration
1726 Alzheimer's disease
1727 Hemorrhagic disorder due to intrinsic circulating anticoagulants
1728 Renal sclerosis, unspecified
1729 Vascular dementia
1730 Polyneuropathy in diseases classified elsewhere
1731 Presence of cardiac defibrillator
1732 Carcinoma in situ of skin
1733 Presence of cardiac device
1734 Cerebral amyloid angiopathy*
1735 Frontotemporal dementia
1736 Ventricular fibrillation and flutter
1737 Hepatorenal syndrome
1738 Abnormal findings in semen
1739 Drug-induced hypoglycemia*
1740 Iatrogenic hypopituitarism*
1741 Ischemic cardiomyopathy*
1742 Chronic atrial fibrillation*
1743 Persistent atrial fibrillation*
1744 Atypical atrial flutter*
1745 Renal dialysis
1746 Kidney transplant
1747 Dementia with Lewy bodies
1748 Permanent atrial fibrillation*
     phecode_category delta        .lower       .upper        .width .point
1    Cardio           -0.486594891 -0.551437407  0.3539902858 0.95   median
2    Blood            -0.262660996 -0.294607645 -0.1240949425 0.95   median
3    Endo             -0.329952095 -0.394441043  0.1727290262 0.95   median
4    ID               -0.442494079 -0.815852612 -0.2483819302 0.95   median
5    Blood            -0.249456515 -0.284687262  0.1978014208 0.95   median
6    Neoplasms        -0.266717171 -0.428702066  0.2210712267 0.95   median
7    Endo             -0.250280463 -0.332260678  0.1205680975 0.95   median
8    Blood            -0.606466499 -0.914215070  0.2477878854 0.95   median
9    Stat             -0.397117471 -0.454792122  0.1961590202 0.95   median
10   ID               -0.247252793 -0.315766984  0.1122195665 0.95   median
11   Stat             -0.303059331 -0.389098646  0.1105247830 0.95   median
12   GI               -0.225940888 -0.272968240  0.1389156567 0.95   median
13   GI               -0.300760953 -0.337423783  0.0849380385 0.95   median
14   Genitourinary    -0.230617223 -0.401739110  0.2541217571 0.95   median
15   Neuro            -0.435748645 -0.462293710 -0.4179966985 0.95   median
16   ID               -0.176110234 -0.306051993 -0.0652080909 0.95   median
17   Mental           -0.136421720 -0.156865281 -0.1113566855 0.95   median
18   Neoplasms        -0.294230747 -0.391726223  0.0104965980 0.95   median
19   GI               -0.274172625 -0.307325244  0.0782069477 0.95   median
20   Musc/Skel        -0.156689342 -0.508709978  0.0661235137 0.95   median
21   ID               -0.272915372 -0.306930054  0.0783951347 0.95   median
22   Blood            -0.343026678 -0.666776871 -0.1208185578 0.95   median
23   ID               -0.447868870 -0.457738357 -0.4290857238 0.95   median
24   ID               -0.198594835 -0.243577520 -0.1597688026 0.95   median
25   ID               -0.194731085 -0.215769698 -0.1745697846 0.95   median
26   Neoplasms        -0.105187110 -0.214223918  0.0782954968 0.95   median
27   ID               -0.056512044 -0.112334060  0.0004559116 0.95   median
28   Neuro            -0.480255413 -0.656401388 -0.2995675347 0.95   median
29   Musc/Skel         0.007867683  0.002008288  0.0131185270 0.95   median
30   Signs/Symptoms   -0.004055798 -0.011067881  0.0018947567 0.95   median
⋮    ⋮                ⋮            ⋮            ⋮             ⋮      ⋮
1719 Derm              0.225854293  0.109211260 0.345155452   0.95   median
1720 Endo              0.236612170  0.221492568 0.251650904   0.95   median
1721 Cardio            0.242531373  0.207438024 0.270190424   0.95   median
1722 Eye               0.254578081  0.233538329 0.279206417   0.95   median
1723 Cardio            0.129893134  0.112257398 0.150598147   0.95   median
1724 Genitourinary     0.251375509  0.235817385 0.272019575   0.95   median
1725 Eye              -0.005851253 -0.027774092 0.017162640   0.95   median
1726 Neuro             0.010711797  0.002307917 0.019078121   0.95   median
1727 Blood             0.158054007  0.127853008 0.191335058   0.95   median
1728 Genitourinary     0.275702638  0.244453847 0.306015309   0.95   median
1729 Neuro             0.055173451  0.041827296 0.067450626   0.95   median
1730 Neuro             0.232086027  0.221714684 0.242423918   0.95   median
1731 Cardio            0.196157569  0.128203969 0.261125911   0.95   median
1732 Neoplasms         0.050241073  0.039963637 0.060705008   0.95   median
1733 Cardio            0.140342310  0.110655441 0.173546367   0.95   median
1734 Metab             0.019015332 -0.023081976 0.057800181   0.95   median
1735 Neuro             0.057624779  0.001353454 0.107581219   0.95   median
1736 Cardio            0.208042258  0.170109711 0.246817423   0.95   median
1737 GI                0.275083244  0.223841033 0.336039266   0.95   median
1738 Genitourinary     0.003220062 -0.001716991 0.007347175   0.95   median
1739 Endo              0.288278244  0.227131903 0.341782979   0.95   median
1740 Endo              0.288409589  0.104657383 0.443746587   0.95   median
1741 Cardio            0.141548658  0.123139341 0.156339565   0.95   median
1742 Cardio            0.107849300  0.097706645 0.121266268   0.95   median
1743 Cardio            0.088258289  0.076943654 0.100764530   0.95   median
1744 Cardio            0.122106563  0.094432895 0.152863219   0.95   median
1745 Genitourinary     0.357421427 -0.315117042 0.443843710   0.95   median
1746 Stat              0.334243299  0.303311612 0.364822576   0.95   median
1747 Neuro             0.051628039  0.014535734 0.087203405   0.95   median
1748 Cardio            0.086468321  0.068625739 0.104524563   0.95   median
     .interval highlight
1    qi        NO
2    qi        NO
3    qi        NO
4    qi        NO
5    qi        NO
6    qi        NO
7    qi        NO
8    qi        NO
9    qi        NO
10   qi        NO
11   qi        NO
12   qi        NO
13   qi        NO
14   qi        NO
15   qi        NO
16   qi        NO
17   qi        NO
18   qi        NO
19   qi        NO
20   qi        NO
21   qi        NO
22   qi        NO
23   qi        NO
24   qi        NO
25   qi        NO
26   qi        NO
27   qi        NO
28   qi        NO
29   qi        NO
30   qi        NO
⋮    ⋮         ⋮
1719 qi        NO
1720 qi        NO
1721 qi        NO
1722 qi        NO
1723 qi        NO
1724 qi        NO
1725 qi        NO
1726 qi        NO
1727 qi        NO
1728 qi        NO
1729 qi        NO
1730 qi        NO
1731 qi        NO
1732 qi        NO
1733 qi        NO
1734 qi        NO
1735 qi        NO
1736 qi        NO
1737 qi        NO
1738 qi        NO
1739 qi        NO
1740 qi        NO
1741 qi        NO
1742 qi        NO
1743 qi        NO
1744 qi        NO
1745 qi        NO
1746 qi        NO
1747 qi        NO
1748 qi        NO

In [ ]:
temp %>% filter(.lower > 0)

     endpoint
1    phecode_724
2    phecode_486
3    phecode_089
4    phecode_504-3
5    phecode_599
6    phecode_821
7    phecode_977
8    phecode_819
9    phecode_734-5
10   phecode_176
11   phecode_089-1
12   phecode_559
13   phecode_387-2
14   phecode_678
15   phecode_124-5
16   phecode_681
17   phecode_460
18   phecode_734
19   phecode_234
20   phecode_402
21   phecode_089-2
22   phecode_475
23   phecode_522
24   phecode_236
25   phecode_236-1
26   phecode_452
27   phecode_552-1
28   phecode_527
29   phecode_473
30   phecode_504-1
⋮    ⋮
1312 phecode_416-221
1313 phecode_123-1
1314 phecode_374-8
1315 phecode_540-4
1316 phecode_688-6
1317 phecode_208-22
1318 phecode_444-13
1319 phecode_374-42
1320 phecode_413-6
1321 phecode_583-1
1322 phecode_328-1
1323 phecode_168-12
1324 phecode_586-5
1325 phecode_328-7
1326 phecode_337-8
1327 phecode_419-2
1328 phecode_103-3
1329 phecode_419
1330 phecode_328-2
1331 phecode_416-3
1332 phecode_542-5
1333 phecode_205-3
1334 phecode_209-23
1335 phecode_414-5
1336 phecode_416-213
1337 phecode_416-212
1338 phecode_416-222
1339 phecode_979-2
1340 phecode_328-4
1341 phecode_416-214
     phecode_string
1    Other symptoms and disorders of the soft tissue
2    Other respiratory disorders
3    Infections
4    Periodontitis
5    Other symptoms/disorders or the urinary system
6    Abnormality of red blood cells
7    Long term (current) drug therapy
8    General symptoms and other findings
9    Inflammatory conditions of jaw
10   Other diseases of blood and blood-forming organs
11   Bacterial infections
12   Other disease of digestive system, NOS
13   Myopia
14   Other skin and connective tissue disorders
15   Essential thrombocythemia
16   Localized swelling, mass and lump of skin and subcutaneous tissue
17   Acute respiratory infection
18   Diseases of the jaws
19   Other nutritional deficiencies
20   Elevated blood pressure reading without diagnosis of hypertension
21   Viral infections
22   Asthma
23   Gastrointestinal inflammation
24   Overweight and obesity
25   Obesity
26   Hemorrhage, NOS
27   Cholangitis
28   Abdominal pain
29   Other diseases of upper respiratory tract
30   Gingivitis
⋮    ⋮
1312 Typical atrial flutter*
1313 Multiple myeloma
1314 Retinal edema
1315 Alcoholic hepatitis
1316 Rheumatoid nodule*
1317 Secondary hyperparathyroidism
1318 Esophageal varix
1319 Diabetic retinopathy
1320 Heart valve replaced
1321 End stage renal disease [CDK, stage 5]
1322 Alzheimer's disease
1323 Hemorrhagic disorder due to intrinsic circulating anticoagulants
1324 Renal sclerosis, unspecified
1325 Vascular dementia
1326 Polyneuropathy in diseases classified elsewhere
1327 Presence of cardiac defibrillator
1328 Carcinoma in situ of skin
1329 Presence of cardiac device
1330 Frontotemporal dementia
1331 Ventricular fibrillation and flutter
1332 Hepatorenal syndrome
1333 Drug-induced hypoglycemia*
1334 Iatrogenic hypopituitarism*
1335 Ischemic cardiomyopathy*
1336 Chronic atrial fibrillation*
1337 Persistent atrial fibrillation*
1338 Atypical atrial flutter*
1339 Kidney transplant
1340 Dementia with Lewy bodies
1341 Permanent atrial fibrillation*
     phecode_category delta       .lower       .upper     .width .point
1    Musc/Skel        0.007867683 0.0020082880 0.01311853 0.95   median
2    Resp             0.048586983 0.0429926555 0.05378074 0.95   median
3    ID               0.010629576 0.0041618792 0.01675308 0.95   median
4    GI               0.032107953 0.0082912811 0.05583427 0.95   median
5    Genitourinary    0.012417266 0.0079220392 0.01768279 0.95   median
6    Signs/Symptoms   0.027566106 0.0198067321 0.03330737 0.95   median
7    Rx               0.016595122 0.0113742091 0.02094760 0.95   median
8    Signs/Symptoms   0.013886132 0.0088453401 0.01827266 0.95   median
9    Musc/Skel        0.044532143 0.0272531326 0.06397998 0.95   median
10   Blood            0.050888420 0.0457645778 0.05558458 0.95   median
11   ID               0.018268296 0.0082796821 0.02845251 0.95   median
12   GI               0.065869883 0.0611735452 0.07128367 0.95   median
13   Eye              0.052818588 0.0426225485 0.06370373 0.95   median
14   Derm             0.071915918 0.0662976152 0.07637663 0.95   median
15   Neoplasms        0.037864204 0.0052970417 0.06875236 0.95   median
16   Derm             0.036269520 0.0314932957 0.04094898 0.95   median
17   Resp             0.023305337 0.0149268816 0.03325304 0.95   median
18   Musc/Skel        0.057187515 0.0456766659 0.06791147 0.95   median
19   Metab            0.008810213 0.0007424708 0.01722162 0.95   median
20   Cardio           0.067934042 0.0578333966 0.07824621 0.95   median
21   ID               0.057579735 0.0510971155 0.06344584 0.95   median
22   Resp             0.019105466 0.0066665621 0.02961578 0.95   median
23   GI               0.045478041 0.0374920270 0.05344918 0.95   median
24   Metab            0.048774102 0.0407615596 0.05606496 0.95   median
25   Metab            0.048808102 0.0406601403 0.05607620 0.95   median
26   Cardio           0.044003738 0.0306420350 0.06194472 0.95   median
27   GI               0.057811297 0.0295269507 0.08563609 0.95   median
28   GI               0.035558115 0.0275268754 0.04266983 0.95   median
29   Resp             0.043299246 0.0333503862 0.05224272 0.95   median
30   GI               0.056830041 0.0364255338 0.08699872 0.95   median
⋮    ⋮                ⋮           ⋮            ⋮          ⋮      ⋮
1312 Cardio           0.08337825  0.059901511  0.10223423 0.95   median
1313 Neoplasms        0.14077949  0.089617023  0.19386253 0.95   median
1314 Eye              0.19934830  0.178403788  0.21943275 0.95   median
1315 GI               0.21839942  0.173005495  0.25971385 0.95   median
1316 Derm             0.22585429  0.109211260  0.34515545 0.95   median
1317 Endo             0.23661217  0.221492568  0.25165090 0.95   median
1318 Cardio           0.24253137  0.207438024  0.27019042 0.95   median
1319 Eye              0.25457808  0.233538329  0.27920642 0.95   median
1320 Cardio           0.12989313  0.112257398  0.15059815 0.95   median
1321 Genitourinary    0.25137551  0.235817385  0.27201958 0.95   median
1322 Neuro            0.01071180  0.002307917  0.01907812 0.95   median
1323 Blood            0.15805401  0.127853008  0.19133506 0.95   median
1324 Genitourinary    0.27570264  0.244453847  0.30601531 0.95   median
1325 Neuro            0.05517345  0.041827296  0.06745063 0.95   median
1326 Neuro            0.23208603  0.221714684  0.24242392 0.95   median
1327 Cardio           0.19615757  0.128203969  0.26112591 0.95   median
1328 Neoplasms        0.05024107  0.039963637  0.06070501 0.95   median
1329 Cardio           0.14034231  0.110655441  0.17354637 0.95   median
1330 Neuro            0.05762478  0.001353454  0.10758122 0.95   median
1331 Cardio           0.20804226  0.170109711  0.24681742 0.95   median
1332 GI               0.27508324  0.223841033  0.33603927 0.95   median
1333 Endo             0.28827824  0.227131903  0.34178298 0.95   median
1334 Endo             0.28840959  0.104657383  0.44374659 0.95   median
1335 Cardio           0.14154866  0.123139341  0.15633956 0.95   median
1336 Cardio           0.10784930  0.097706645  0.12126627 0.95   median
1337 Cardio           0.08825829  0.076943654  0.10076453 0.95   median
1338 Cardio           0.12210656  0.094432895  0.15286322 0.95   median
1339 Stat             0.33424330  0.303311612  0.36482258 0.95   median
1340 Neuro            0.05162804  0.014535734  0.08720341 0.95   median
1341 Cardio           0.08646832  0.068625739  0.10452456 0.95   median
     .interval highlight
1    qi        NO
2    qi        NO
3    qi        NO
4    qi        NO
5    qi        NO
6    qi        NO
7    qi        NO
8    qi        NO
9    qi        NO
10   qi        NO
11   qi        NO
12   qi        NO
13   qi        NO
14   qi        NO
15   qi        NO
16   qi        NO
17   qi        NO
18   qi        NO
19   qi        NO
20   qi        NO
21   qi        NO
22   qi        NO
23   qi        NO
24   qi        NO
25   qi        NO
26   qi        NO
27   qi        NO
28   qi        NO
29   qi        NO
30   qi        NO
⋮    ⋮         ⋮
1312 qi        NO
1313 qi        NO
1314 qi        NO
1315 qi        NO
1316 qi        NO
1317 qi        NO
1318 qi        NO
1319 qi        NO
1320 qi        NO
1321 qi        NO
1322 qi        NO
1323 qi        NO
1324 qi        NO
1325 qi        NO
1326 qi        NO
1327 qi        NO
1328 qi        NO
1329 qi        NO
1330 qi        NO
1331 qi        NO
1332 qi        NO
1333 qi        NO
1334 qi        NO
1335 qi        NO
1336 qi        NO
1337 qi        NO
1338 qi        NO
1339 qi        NO
1340 qi        NO
1341 qi        NO

In [ ]:
options(digits = 3) 

temp_num_events %>%
    filter(endpoint %in% endpoint_selection) %>%
    arrange(delta.lower)

   endpoint       phecode_string
1  phecode_401    Hypertension
2  phecode_324-11 Parkinson's disease (Primary)
3  phecode_438-11 Abdominal aortic aneurysm
4  phecode_416-21 Atrial fibrillation
5  phecode_404    Ischemic heart disease
6  phecode_665    Psoriasis
7  phecode_410-2  Endocarditis
8  phecode_413-21 Aortic stenosis
9  phecode_284    Suicide ideation and attempt or self harm
10 phecode_400    Rheumatic fever and chronic rheumatic heart diseases
11 phecode_718    Back pain
12 phecode_705-1  Rheumatoid arthritis
13 phecode_202    Diabetes mellitus
14 phecode_431-11 Cerebral infarction [Ischemic stroke]
15 phecode_583    Chronic kidney disease
16 phecode_164    Anemia
17 phecode_413-11 Mitral valve insufficiency
18 phecode_474    Chronic obstructive pulmonary disease [COPD]
19 phecode_404-1  Myocardial infarction [Heart attack]
20 phecode_468    Pneumonia
21 phecode_424    Heart failure
22 OMOP_4306655   All-Cause Death
23 phecode_440-3  Pulmonary embolism
24 phecode_420    Cardiac arrest
   phecode_category num_events num_events.lower num_events.upper delta
1  Cardio           13853      13629            14087            0.0164
2  Neuro              452        416              492            0.0324
3  Cardio             613        569              660            0.0323
4  Cardio            3802       3699             3919            0.0438
5  Cardio            7699       7534             7880            0.0545
6  Derm              1169       1105             1234            0.0700
7  Cardio            5238       5106             5385            0.0593
8  Cardio             178        155              204            0.0785
9  Mental            2266       2180             2347            0.0727
10 Cardio            3851       3736             3974            0.0700
11 Musc/Skel        16453      16254            16701            0.0769
12 Musc/Skel         1201       1138             1270            0.0869
13 Endo              7651       7486             7804            0.0801
14 Cardio            2330       2231             2420            0.0810
15 Genitourinary     5866       5723             6021            0.0860
16 Blood            13834      13619            14114            0.0876
17 Cardio            2486       2394             2585            0.0930
18 Resp              4455       4334             4596            0.0933
19 Cardio            3110       3006             3200            0.1052
20 Resp              7128       6969             7289            0.1026
21 Cardio            4818       4680             4962            0.1077
22 Death             2431       2334             2513            0.1137
23 Cardio            1970       1885             2063            0.1210
24 Cardio             825        775              878            0.1755
   delta.lower delta.upper score1 score1.lower score1.upper score2 score2.lower
1  0.0128      0.0194      0.627  0.623        0.632        0.643  0.639
2  0.0211      0.0430      0.817  0.800        0.834        0.849  0.832
3  0.0217      0.0442      0.813  0.800        0.828        0.846  0.833
4  0.0371      0.0500      0.753  0.746        0.760        0.796  0.790
5  0.0496      0.0595      0.708  0.702        0.712        0.762  0.757
6  0.0507      0.0914      0.551  0.536        0.564        0.621  0.607
7  0.0522      0.0661      0.706  0.699        0.712        0.765  0.758
8  0.0562      0.0999      0.787  0.758        0.814        0.866  0.846
9  0.0578      0.0871      0.661  0.650        0.671        0.733  0.720
10 0.0637      0.0776      0.703  0.696        0.710        0.773  0.766
11 0.0709      0.0819      0.541  0.537        0.545        0.618  0.614
12 0.0716      0.1068      0.647  0.635        0.660        0.735  0.722
13 0.0722      0.0869      0.564  0.558        0.569        0.644  0.637
14 0.0733      0.0890      0.687  0.676        0.695        0.767  0.758
15 0.0804      0.0919      0.692  0.685        0.698        0.778  0.772
16 0.0834      0.0925      0.530  0.526        0.535        0.618  0.613
17 0.0842      0.1005      0.717  0.709        0.727        0.810  0.803
18 0.0851      0.1009      0.661  0.654        0.668        0.754  0.748
19 0.0970      0.1136      0.689  0.683        0.698        0.795  0.788
20 0.0975      0.1080      0.590  0.583        0.597        0.693  0.687
21 0.1010      0.1135      0.703  0.697        0.710        0.811  0.805
22 0.1039      0.1220      0.693  0.685        0.704        0.807  0.799
23 0.1092      0.1325      0.590  0.578        0.603        0.711  0.701
24 0.1583      0.1945      0.641  0.625        0.659        0.818  0.804
   score2.upper .width .point .interval highlight
1  0.648        0.95   median qi        YES
2  0.863        0.95   median qi        YES
3  0.860        0.95   median qi        YES
4  0.803        0.95   median qi        YES
5  0.767        0.95   median qi        YES
6  0.635        0.95   median qi        YES
7  0.771        0.95   median qi        YES
8  0.886        0.95   median qi        YES
9  0.746        0.95   median qi        YES
10 0.781        0.95   median qi        YES
11 0.622        0.95   median qi        YES
12 0.749        0.95   median qi        YES
13 0.651        0.95   median qi        YES
14 0.776        0.95   median qi        YES
15 0.784        0.95   median qi        YES
16 0.623        0.95   median qi        YES
17 0.818        0.95   median qi        YES
18 0.760        0.95   median qi        YES
19 0.803        0.95   median qi        YES
20 0.699        0.95   median qi        YES
21 0.817        0.95   median qi        YES
22 0.815        0.95   median qi        YES
23 0.723        0.95   median qi        YES
24 0.831        0.95   median qi        YES

In [ ]:
endpoint_order = (temp %>% arrange(delta))$endpoint

temp = temp %>% mutate(endpoint = factor(endpoint, levels=endpoint_order)) %>% ungroup() %>%
    arrange(endpoint) %>% group_by(phecode_category) %>% mutate(endpoint = row_number()) %>%
    filter(!phecode_category %in% c("Signs/Symptoms", "Preg", "Rx", "Stat"))

In [ ]:
overview = ggplot(temp) +
    geom_ribbon(aes(x=endpoint, ymin=0, ymax=delta), fill="black", alpha=0.2)+
    geom_point(aes(x=endpoint, y=delta, color=highlight, size=highlight, alpha=highlight)) +
    geom_text(data=temp %>% filter(highlight=="YES"), aes(x=endpoint, y=delta+0.1, label="↓"), color="black", size=5, alpha=0.7) +
    #geom_segment(aes(x=endpoint, xend=endpoint, y=0, yend=delta, color=highlight, size=highlight), alpha=0.5)+#+
    labs(x="Endpoints", y="Delta C-Index")+
    scale_color_manual(values=c("NO"="black", "YES"="firebrick"))+
    scale_alpha_manual(values=c("NO"=0.1, "YES"=1))+
    scale_size_manual(values=c("NO"=0.01, "YES"=1))+
    #scale_colour_manual(values = c("pos"="forestgreen", "neg" = "firebrick")) +
    #coord_polar() +
    coord_cartesian(ylim=c(-0.3, 0.3), clip = "off")+
    scale_y_continuous(expand=c(0, 0))+
    scale_x_discrete(expand=expansion(add=20))+
    facet_grid(~phecode_category, scales="free_x", space="free_x")+#, switch=TRUE)+
    #facet_grid2(~phecode_category, scales = "free", independent = "all") +
    theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        panel.grid.major=element_blank(),
         strip.text = element_text(angle=270, hjust=1)) +
    theme(legend.position="none")

    #geom_ribbon(aes(x=id, ymin=AgeSex, ymax=`Age+Sex+MedicalHistory`), fill="red", alpha=0.2)
#geom_violin(size=0.1)
overview

In [ ]:
#library(gt)
figure_path = "/sc-projects/sc-proj-ukb-cvd/results/projects/22_medical_records/figures/220823_allofus/"
plot_name = "Figure5a_overview"
overview %>% ggsave(filename=glue("{figure_path}/{plot_name}.png"), device="png", width=plot_width, height=plot_height, dpi=plot_res)

In [ ]:
base_size = 8
title_size = 10
facet_size = 9
geom_text_size=3
theme_set(theme_classic(base_size = base_size) +
          theme(strip.background = element_blank(), plot.title=element_text(size=title_size, hjust=0),
                strip.text.x = element_text(size = facet_size),axis.title=element_text(size=10), axis.text=element_text(size=8, color="black"),
                legend.position="bottom", axis.line = element_line(size = 0.2), axis.ticks=element_line(size=0.2), panel.grid.major=element_line()))

In [ ]:
plot_width = 8.25; plot_height=2; plot_res = 320
options(repr.plot.width = plot_width, repr.plot.height = plot_height, repr.plot.res=plot_res)

plot_against_score = function(score1, score2, endpoint_order=c()){

  scores_plot = c(score1, score2)#, "AgeSexMedicalHistory"

  score_label = glue("{score1} vs. {score2}")
  #print(score_label)

  temp = benchmark_endpoints %>%
      filter(score %in% scores_plot) %>%
      filter(endpoint %in% endpoint_selection) %>%
      mutate(score = factor(score, levels=scores_plot)) %>%
      mutate(endpoint = factor(endpoint, levels=sort(endpoint_selection))) %>%
      group_by(endpoint, score, phecode_string, phecode_category) %>%
      ungroup() %>%
      pivot_wider(names_from=score, values_from=cindex, id_cols=c(uuid, partition, endpoint, phecode_category, phecode_string)) %>%
      mutate(id = row_number()) %>%
      mutate(delta = !!sym(score2)-!!sym(score1)) %>%
      mutate(pos = case_when(delta>=0 ~ "pos", delta < 0 ~"neg")) %>%
      mutate(endpoint = fct_reorder(endpoint, delta)) %>%
      mutate(highlight = case_when(endpoint %in% endpoint_selection ~ "YES", TRUE ~ "NO")) %>%# %>% filter(endpoint %in% endpoint_sample)
      mutate(phecode_category = factor(phecode_category, levels=categories_sorted)) %>%
      filter(endpoint %in% endpoint_selection) #%>% mutate(endpoint=factor(endpoint, levels=endpoint_order_diff))

  temp_abs = temp %>% group_by(endpoint) %>% summarise(delta=median(delta), m_score2=median(!!sym(score2)), m_score1=median(!!sym(score1))) %>% ungroup()
  #print(levels(temp_abs$endpoint))

  temp_abs_segment = temp_abs %>% rowwise() %>% mutate(min_cindex = min(m_score1, m_score2), max_cindex=max(m_score1, m_score2)) %>% ungroup()# %>% filter(abs(min_cindex-max_cindex)>0.02)

  endpoint_order = (temp %>% group_by(endpoint) %>% summarise(delta=median(delta)) %>% arrange(delta))$endpoint
  print(endpoint_order)

  if (length(endpoint_order)>0){
      temp = temp %>% filter(endpoint %in% endpoint_order) %>% mutate(endpoint=factor(endpoint, levels=endpoint_order))
      temp_abs = temp_abs %>% filter(endpoint %in% endpoint_order) %>% mutate(endpoint=factor(endpoint, levels=endpoint_order))
      temp_abs_segment = temp_abs_segment %>% filter(endpoint %in% endpoint_order) %>% mutate(endpoint=factor(endpoint, levels=endpoint_order))
      }
  #print(temp_abs_segment)

  abs = ggplot(temp_abs) +
      #geom_violin(aes(x=fct_rev(endpoint), y=delta), size=0.5) +
      labs(y="Concordance Index")+

      #geom_segment(data=temp_abs_segment, mapping=aes(x=endpoint, xend=endpoint, y=min_cindex+0.01, yend=max_cindex-0.01), alpha=0.4)+#, arrow = arrow(length = unit(0.01, "npc")), arrow.fill="black")+#+


      geom_point(aes(x=fct_rev(endpoint), y=m_score1), size=1, color="black", alpha=0.7)+
      #geom_point(aes(x=fct_rev(endpoint), y=m_asm), size=1, color="#023768", alpha=0.7)+
      geom_point(aes(x=fct_rev(endpoint), y=m_score2), size=1.5, color="firebrick", alpha=0.7)+
      geom_segment(data=temp_abs %>% filter(abs(delta)>0.02) %>% mutate(endpoint=factor(endpoint, levels=endpoint_order)),
                   aes(x=fct_rev(endpoint), xend=fct_rev(endpoint), y=m_score1+0.01, yend=m_score2-0.01), alpha=0.2, arrow = arrow(length = unit(0.01, "npc")), arrow.fill="black")+#,

      scale_x_discrete(labels=endpoint_map) +

      coord_flip(ylim=c(0.5, 0.9))+
       theme(strip.text = element_text(angle=270), axis.title.y=element_blank()) +
      theme(legend.position="none")

      #geom_ribbon(aes(x=id, ymin=AgeSex, ymax=`Age+Sex+MedicalHistory`), fill="red", alpha=0.2)
  #geom_violin(size=0.1)
  rel = ggplot(temp) +
      #geom_violin(aes(x=fct_rev(endpoint), y=delta), size=0.5) +
      labs(y="Difference in Concordance Index")+
      geom_hline(yintercept=0, size=0.25, alpha=0.5, linetype="22") +
      stat_pointinterval(aes(x=fct_rev(endpoint), y=delta), size=0.5, alpha=0.7)+

      theme(axis.title.y=element_blank(),
          axis.text.y=element_blank(),
         axis.ticks.y=element_blank()) +
      coord_flip(ylim=c(-0.01, 0.23))+
       theme(strip.text = element_text(angle=270)) +
      theme(legend.position="none")

      #geom_ribbon(aes(x=id, ymin=AgeSex, ymax=`Age+Sex+MedicalHistory`), fill="red", alpha=0.2)
  #geom_violin(size=0.1)
  return(abs|rel)
}

In [ ]:
ase_size = 8
title_size = 10
facet_size = 9
geom_text_size=3
theme_set(theme_classic(base_size = base_size) +
          theme(strip.background = element_blank(), plot.title=element_text(size=title_size, hjust=0),
                strip.text.x = element_text(size = facet_size),axis.title=element_text(size=10), axis.text=element_text(size=8, color="black"),
                legend.position="bottom", axis.line = element_line(size = 0.2), axis.ticks=element_line(size=0.2), panel.grid.major=element_line()))

endpoint_order=c()
length(endpoint_order)

In [ ]:
plot_width = 8.25; plot_height=3.25; plot_res = 320
options(repr.plot.width = plot_width, repr.plot.height = plot_height, repr.plot.res=plot_res)

fig5b = plot_against_score("AgeSex_AoUCPH", "AgeSex+MedicalHistory_UKBBParams")

plot_name = "Figure5b_performances"
fig5b %>% ggsave(filename=glue("{figure_path}/{plot_name}.png"), device="png", width=plot_width, height=plot_height, dpi=plot_res)