# Benchmarks

## Initialize

In [1]:
#library(Rmisc)
library(dtplyr)
library(tidyverse)
library(glue)
library(arrow)
library(patchwork)
library(data.table)
library("jsonlite")
library(ggthemes)

Warning message:
“package ‘dtplyr’ was built under R version 4.0.5”
Warning message:
“package ‘tidyverse’ was built under R version 4.0.5”
── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.3.6      ✔ purrr   0.3.5
✔ tibble  3.1.8      ✔ dplyr   1.0.10
✔ tidyr   1.2.1      ✔ stringr 1.5.0
✔ readr   2.1.2      ✔ forcats 0.5.2
Warning message:
“package ‘ggplot2’ was built under R version 4.0.5”
Warning message:
“package ‘tibble’ was built under R version 4.0.5”
Warning message:
“package ‘tidyr’ was built under R version 4.0.5”
Warning message:
“package ‘readr’ was built under R version 4.0.5”
Warning message:
“package ‘dplyr’ was built under R version 4.0.5”
Warning message:
“package ‘forcats’ was built under R version 4.0.5”
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
Warning message:
“package ‘glue’ was built under R version 4.0.5”
Warning message:
“package ‘arrow’ was built under R version 4.0.3”

Attaching package: ‘arrow’


The following object is masked from ‘package:utils’:

    timestamp


Warning message:
“package ‘data.table’ was built under R version 4.0.5”

Attaching package: ‘data.table’


The following objects are masked from ‘package:dplyr’:

    between, first, last


The following object is masked from ‘package:purrr’:

    transpose


Warning message:
“package ‘jsonlite’ was built under R version 4.0.5”

Attaching package: ‘jsonlite’


The following object is masked from ‘package:purrr’:

    flatten


Warning message:
“package ‘ggthemes’ was built under R version 4.0.3”

In [2]:
if (grepl("sc", Sys.info()[["nodename"]], fixed=TRUE)) {
    base_path = "/sc-projects/sc-proj-ukb-cvd"
} else {
    base_path = "/data/analysis/ag-reils/ag-reils-shared/cardioRS"}
print(base_path)

project_label="22_medical_records"
project_path = glue("{base_path}/results/projects/{project_label}")
figure_path = glue("{project_path}/figures")
output_path = glue("{project_path}/data")

experiment = 230425
experiment_path = glue("{output_path}/{experiment}")

[1] "/sc-projects/sc-proj-ukb-cvd"

In [3]:
base_size = 8
title_size = 10
facet_size = 10
geom_text_size=3
theme_set(theme_classic(base_size = base_size) + 
          theme(strip.background = element_blank(), plot.title=element_text(size=title_size, hjust=0), 
                strip.text.x = element_text(size = facet_size),axis.title=element_text(size=10), axis.text=element_text(size=8, color="black"),
                legend.position="bottom", axis.line = element_line(size = 0.2), axis.ticks=element_line(size=0.2), panel.grid.major=element_line()))

In [4]:
colors_dict = read_json("colors.json")
color_map <- c(
    "Identity(AgeSex)+MLP" = colors_dict$pastel$red$mid,
    "Identity(Records)+MLP" = colors_dict$pastel$red$mid,
    "GNN(Records)+MLP" = colors_dict$pastel$red$mid,
    "Identity(AgeSex+Records)+MLP" = colors_dict$pastel$red$mid,
    "GNN(AgeSex+Records)+MLP" = colors_dict$pastel$red$mid
)

In [5]:
endpoint_defs = arrow::read_feather(glue("{output_path}/phecode_defs_220306.feather")) %>% arrange(endpoint)

In [6]:
endpoint_map = endpoint_defs$phecode_string
names(endpoint_map) =  endpoint_defs$endpoint
#endpoint_order_freq = (outcome_freq %>% arrange(desc(freq)))$endpoint

In [7]:
endpoint_order = (endpoint_defs %>% arrange(as.numeric(phecode)))$endpoint

In [8]:
endpoint_selection = c(
'phecode_164',
'phecode_179',
'phecode_202-2',
'phecode_284',
'phecode_401',
'phecode_404-1',
'phecode_413-21',
'phecode_413-32',
'phecode_416-21',
'phecode_420',
'phecode_424',
'phecode_431-1',
'phecode_438-6',
'phecode_440-3',
'phecode_444-13',
'phecode_448',
'phecode_468',
'phecode_474',
'phecode_542-4',
'phecode_583',
'phecode_665-1',
'phecode_705-1',
'phecode_718',
'OMOP_4306655'
    )

## Load data

# Load Benchmarks

In [9]:
name = "hrs_endpoints"
hrs_endpoints = arrow::read_feather(glue("{experiment_path}/{name}.feather"), col_select=c("endpoint", "score", "partition", "hrs_mh", "hrs_mh_age", "hrs_mh_sex")) %>% left_join(endpoint_defs)

Joining, by = "endpoint"

In [10]:
hrs_endpoints

       endpoint      score                                partition hrs_mh
1      OMOP_4306655  ASCVD+MedicalHistory                 0         2.630058
2      OMOP_4306655  ASCVD+MedicalHistory                 1         2.627838
3      OMOP_4306655  ASCVD+MedicalHistory                 2         2.706116
4      OMOP_4306655  ASCVD+MedicalHistory                 3         2.700938
5      OMOP_4306655  ASCVD+MedicalHistory                 4         2.612606
6      OMOP_4306655  ASCVD+MedicalHistory                 5         2.625049
7      OMOP_4306655  ASCVD+MedicalHistory                 6         2.724130
8      OMOP_4306655  ASCVD+MedicalHistory                 7         2.781958
9      OMOP_4306655  ASCVD+MedicalHistory                 8         2.702470
10     OMOP_4306655  ASCVD+MedicalHistory                 9         2.767540
11     OMOP_4306655  ASCVD+MedicalHistory                 10        2.683536
12     OMOP_4306655  ASCVD+MedicalHistory                 11        2.741360
13     OMOP_4306655  ASCVD+MedicalHistory                 12        2.729932
14     OMOP_4306655  ASCVD+MedicalHistory                 13        2.671174
15     OMOP_4306655  ASCVD+MedicalHistory                 14        2.760730
16     OMOP_4306655  ASCVD+MedicalHistory                 15        2.681578
17     OMOP_4306655  ASCVD+MedicalHistory                 16        2.610182
18     OMOP_4306655  ASCVD+MedicalHistory                 17        2.664844
19     OMOP_4306655  ASCVD+MedicalHistory                 18        2.593229
20     OMOP_4306655  ASCVD+MedicalHistory                 19        2.637880
21     OMOP_4306655  ASCVD+MedicalHistory                 20        2.647081
22     OMOP_4306655  ASCVD+MedicalHistory                 21        2.681810
23     OMOP_4306655  Age+Sex+Comorbidities+MedicalHistory 0         2.724409
24     OMOP_4306655  Age+Sex+Comorbidities+MedicalHistory 1         2.738987
25     OMOP_4306655  Age+Sex+Comorbidities+MedicalHistory 2         2.778256
26     OMOP_4306655  Age+Sex+Comorbidities+MedicalHistory 3         2.779690
27     OMOP_4306655  Age+Sex+Comorbidities+MedicalHistory 4         2.711358
28     OMOP_4306655  Age+Sex+Comorbidities+MedicalHistory 5         2.727607
29     OMOP_4306655  Age+Sex+Comorbidities+MedicalHistory 6         2.837157
30     OMOP_4306655  Age+Sex+Comorbidities+MedicalHistory 7         2.888678
⋮      ⋮             ⋮                                    ⋮         ⋮
372805 phecode_979-7 QRISK3+MedicalHistory                14        2.9804688
372806 phecode_979-7 QRISK3+MedicalHistory                15        2.8071655
372807 phecode_979-7 QRISK3+MedicalHistory                16        0.7632269
372808 phecode_979-7 QRISK3+MedicalHistory                17        2.6669510
372809 phecode_979-7 QRISK3+MedicalHistory                18        2.7988693
372810 phecode_979-7 QRISK3+MedicalHistory                19        2.8312608
372811 phecode_979-7 QRISK3+MedicalHistory                20        0.6462974
372812 phecode_979-7 QRISK3+MedicalHistory                21        2.8311480
372813 phecode_979-7 SCORE2+MedicalHistory                0         2.9936383
372814 phecode_979-7 SCORE2+MedicalHistory                1         2.6617123
372815 phecode_979-7 SCORE2+MedicalHistory                2         2.6723927
372816 phecode_979-7 SCORE2+MedicalHistory                3         2.7058651
372817 phecode_979-7 SCORE2+MedicalHistory                4         2.8216346
372818 phecode_979-7 SCORE2+MedicalHistory                5         2.8026950
372819 phecode_979-7 SCORE2+MedicalHistory                6         2.8676102
372820 phecode_979-7 SCORE2+MedicalHistory                7         2.7237674
372821 phecode_979-7 SCORE2+MedicalHistory                8         2.7459159
372822 phecode_979-7 SCORE2+MedicalHistory                9         2.8424895
372823 phecode_979-7 SCORE2+MedicalHistory                10        2.8860117
372824 phecode_979-7 SCORE2+MedicalHistory                11        2.8621457
372825 phecode_979-7 SCORE2+MedicalHistory                12        2.8651821
372826 phecode_979-7 SCORE2+MedicalHistory                13        2.8463502
372827 phecode_979-7 SCORE2+MedicalHistory                14        2.9463669
372828 phecode_979-7 SCORE2+MedicalHistory                15        2.7780201
372829 phecode_979-7 SCORE2+MedicalHistory                16        2.8520975
372830 phecode_979-7 SCORE2+MedicalHistory                17        2.6400810
372831 phecode_979-7 SCORE2+MedicalHistory                18        2.7465903
372832 phecode_979-7 SCORE2+MedicalHistory                19        2.8113601
372833 phecode_979-7 SCORE2+MedicalHistory                20        2.7303478
372834 phecode_979-7 SCORE2+MedicalHistory                21        2.8062345
       hrs_mh_age hrs_mh_sex phecode phecode_string         phecode_category
1      NA         NA         4306655 All-Cause Death        Death
2      NA         NA         4306655 All-Cause Death        Death
3      NA         NA         4306655 All-Cause Death        Death
4      NA         NA         4306655 All-Cause Death        Death
5      NA         NA         4306655 All-Cause Death        Death
6      NA         NA         4306655 All-Cause Death        Death
7      NA         NA         4306655 All-Cause Death        Death
8      NA         NA         4306655 All-Cause Death        Death
9      NA         NA         4306655 All-Cause Death        Death
10     NA         NA         4306655 All-Cause Death        Death
11     NA         NA         4306655 All-Cause Death        Death
12     NA         NA         4306655 All-Cause Death        Death
13     NA         NA         4306655 All-Cause Death        Death
14     NA         NA         4306655 All-Cause Death        Death
15     NA         NA         4306655 All-Cause Death        Death
16     NA         NA         4306655 All-Cause Death        Death
17     NA         NA         4306655 All-Cause Death        Death
18     NA         NA         4306655 All-Cause Death        Death
19     NA         NA         4306655 All-Cause Death        Death
20     NA         NA         4306655 All-Cause Death        Death
21     NA         NA         4306655 All-Cause Death        Death
22     NA         NA         4306655 All-Cause Death        Death
23     NA         NA         4306655 All-Cause Death        Death
24     NA         NA         4306655 All-Cause Death        Death
25     NA         NA         4306655 All-Cause Death        Death
26     NA         NA         4306655 All-Cause Death        Death
27     NA         NA         4306655 All-Cause Death        Death
28     NA         NA         4306655 All-Cause Death        Death
29     NA         NA         4306655 All-Cause Death        Death
30     NA         NA         4306655 All-Cause Death        Death
⋮      ⋮          ⋮          ⋮       ⋮                      ⋮
372805 NA         NA         979.7   Bone marrow transplant Stat
372806 NA         NA         979.7   Bone marrow transplant Stat
372807 NA         NA         979.7   Bone marrow transplant Stat
372808 NA         NA         979.7   Bone marrow transplant Stat
372809 NA         NA         979.7   Bone marrow transplant Stat
372810 NA         NA         979.7   Bone marrow transplant Stat
372811 NA         NA         979.7   Bone marrow transplant Stat
372812 NA         NA         979.7   Bone marrow transplant Stat
372813 NA         NA         979.7   Bone marrow transplant Stat
372814 NA         NA         979.7   Bone marrow transplant Stat
372815 NA         NA         979.7   Bone marrow transplant Stat
372816 NA         NA         979.7   Bone marrow transplant Stat
372817 NA         NA         979.7   Bone marrow transplant Stat
372818 NA         NA         979.7   Bone marrow transplant Stat
372819 NA         NA         979.7   Bone marrow transplant Stat
372820 NA         NA         979.7   Bone marrow transplant Stat
372821 NA         NA         979.7   Bone marrow transplant Stat
372822 NA         NA         979.7   Bone marrow transplant Stat
372823 NA         NA         979.7   Bone marrow transplant Stat
372824 NA         NA         979.7   Bone marrow transplant Stat
372825 NA         NA         979.7   Bone marrow transplant Stat
372826 NA         NA         979.7   Bone marrow transplant Stat
372827 NA         NA         979.7   Bone marrow transplant Stat
372828 NA         NA         979.7   Bone marrow transplant Stat
372829 NA         NA         979.7   Bone marrow transplant Stat
372830 NA         NA         979.7   Bone marrow transplant Stat
372831 NA         NA         979.7   Bone marrow transplant Stat
372832 NA         NA         979.7   Bone marrow transplant Stat
372833 NA         NA         979.7   Bone marrow transplant Stat
372834 NA         NA         979.7   Bone marrow transplant Stat
       sex  ICD10_only phecode_top leaf
1      Both NA         NA          NA
2      Both NA         NA          NA
3      Both NA         NA          NA
4      Both NA         NA          NA
5      Both NA         NA          NA
6      Both NA         NA          NA
7      Both NA         NA          NA
8      Both NA         NA          NA
9      Both NA         NA          NA
10     Both NA         NA          NA
11     Both NA         NA          NA
12     Both NA         NA          NA
13     Both NA         NA          NA
14     Both NA         NA          NA
15     Both NA         NA          NA
16     Both NA         NA          NA
17     Both NA         NA          NA
18     Both NA         NA          NA
19     Both NA         NA          NA
20     Both NA         NA          NA
21     Both NA         NA          NA
22     Both NA         NA          NA
23     Both NA         NA          NA
24     Both NA         NA          NA
25     Both NA         NA          NA
26     Both NA         NA          NA
27     Both NA         NA          NA
28     Both NA         NA          NA
29     Both NA         NA          NA
30     Both NA         NA          NA
⋮      ⋮    ⋮          ⋮           ⋮
372805 Both 0          979         1
372806 Both 0          979         1
372807 Both 0          979         1
372808 Both 0          979         1
372809 Both 0          979         1
372810 Both 0          979         1
372811 Both 0          979         1
372812 Both 0          979         1
372813 Both 0          979         1
372814 Both 0          979         1
372815 Both 0          979         1
372816 Both 0          979         1
372817 Both 0          979         1
372818 Both 0          979         1
372819 Both 0          979         1
372820 Both 0          979         1
372821 Both 0          979         1
372822 Both 0          979         1
372823 Both 0          979         1
372824 Both 0          979         1
372825 Both 0          979         1
372826 Both 0          979         1
372827 Both 0          979         1
372828 Both 0          979         1
372829 Both 0          979         1
372830 Both 0          979         1
372831 Both 0          979         1
372832 Both 0          979         1
372833 Both 0          979         1
372834 Both 0          979         1

hrs_endpoints %>% filter(score %in% c("Age+Sex+MedicalHistory", "MedicalHistory")) %>% group_by(endpoint) %>% tally()# %>% arrange(n)

In [11]:
hrs = hrs_endpoints %>% 
    group_by(endpoint, score, phecode_string, phecode_category) %>% 
    #filter(score %in% c("MedicalHistory", "Age+Sex+MedicalHistory", "Age+Sex+MedicalHistory+I(Age*MH)")) %>%
    #mutate(endpoint = factor(endpoint, levels=endpoints_sorted)) %>%
    #mutate(phecode_category = factor(phecode_category, levels=pcats_sorted)) %>%
    select(endpoint, score, hrs_mh, hrs_mh_age, hrs_mh_sex, phecode_string, phecode_category) %>%
    ungroup()
hrs

       endpoint      score                                hrs_mh    hrs_mh_age
1      OMOP_4306655  ASCVD+MedicalHistory                 2.630058  NA
2      OMOP_4306655  ASCVD+MedicalHistory                 2.627838  NA
3      OMOP_4306655  ASCVD+MedicalHistory                 2.706116  NA
4      OMOP_4306655  ASCVD+MedicalHistory                 2.700938  NA
5      OMOP_4306655  ASCVD+MedicalHistory                 2.612606  NA
6      OMOP_4306655  ASCVD+MedicalHistory                 2.625049  NA
7      OMOP_4306655  ASCVD+MedicalHistory                 2.724130  NA
8      OMOP_4306655  ASCVD+MedicalHistory                 2.781958  NA
9      OMOP_4306655  ASCVD+MedicalHistory                 2.702470  NA
10     OMOP_4306655  ASCVD+MedicalHistory                 2.767540  NA
11     OMOP_4306655  ASCVD+MedicalHistory                 2.683536  NA
12     OMOP_4306655  ASCVD+MedicalHistory                 2.741360  NA
13     OMOP_4306655  ASCVD+MedicalHistory                 2.729932  NA
14     OMOP_4306655  ASCVD+MedicalHistory                 2.671174  NA
15     OMOP_4306655  ASCVD+MedicalHistory                 2.760730  NA
16     OMOP_4306655  ASCVD+MedicalHistory                 2.681578  NA
17     OMOP_4306655  ASCVD+MedicalHistory                 2.610182  NA
18     OMOP_4306655  ASCVD+MedicalHistory                 2.664844  NA
19     OMOP_4306655  ASCVD+MedicalHistory                 2.593229  NA
20     OMOP_4306655  ASCVD+MedicalHistory                 2.637880  NA
21     OMOP_4306655  ASCVD+MedicalHistory                 2.647081  NA
22     OMOP_4306655  ASCVD+MedicalHistory                 2.681810  NA
23     OMOP_4306655  Age+Sex+Comorbidities+MedicalHistory 2.724409  NA
24     OMOP_4306655  Age+Sex+Comorbidities+MedicalHistory 2.738987  NA
25     OMOP_4306655  Age+Sex+Comorbidities+MedicalHistory 2.778256  NA
26     OMOP_4306655  Age+Sex+Comorbidities+MedicalHistory 2.779690  NA
27     OMOP_4306655  Age+Sex+Comorbidities+MedicalHistory 2.711358  NA
28     OMOP_4306655  Age+Sex+Comorbidities+MedicalHistory 2.727607  NA
29     OMOP_4306655  Age+Sex+Comorbidities+MedicalHistory 2.837157  NA
30     OMOP_4306655  Age+Sex+Comorbidities+MedicalHistory 2.888678  NA
⋮      ⋮             ⋮                                    ⋮         ⋮
372805 phecode_979-7 QRISK3+MedicalHistory                2.9804688 NA
372806 phecode_979-7 QRISK3+MedicalHistory                2.8071655 NA
372807 phecode_979-7 QRISK3+MedicalHistory                0.7632269 NA
372808 phecode_979-7 QRISK3+MedicalHistory                2.6669510 NA
372809 phecode_979-7 QRISK3+MedicalHistory                2.7988693 NA
372810 phecode_979-7 QRISK3+MedicalHistory                2.8312608 NA
372811 phecode_979-7 QRISK3+MedicalHistory                0.6462974 NA
372812 phecode_979-7 QRISK3+MedicalHistory                2.8311480 NA
372813 phecode_979-7 SCORE2+MedicalHistory                2.9936383 NA
372814 phecode_979-7 SCORE2+MedicalHistory                2.6617123 NA
372815 phecode_979-7 SCORE2+MedicalHistory                2.6723927 NA
372816 phecode_979-7 SCORE2+MedicalHistory                2.7058651 NA
372817 phecode_979-7 SCORE2+MedicalHistory                2.8216346 NA
372818 phecode_979-7 SCORE2+MedicalHistory                2.8026950 NA
372819 phecode_979-7 SCORE2+MedicalHistory                2.8676102 NA
372820 phecode_979-7 SCORE2+MedicalHistory                2.7237674 NA
372821 phecode_979-7 SCORE2+MedicalHistory                2.7459159 NA
372822 phecode_979-7 SCORE2+MedicalHistory                2.8424895 NA
372823 phecode_979-7 SCORE2+MedicalHistory                2.8860117 NA
372824 phecode_979-7 SCORE2+MedicalHistory                2.8621457 NA
372825 phecode_979-7 SCORE2+MedicalHistory                2.8651821 NA
372826 phecode_979-7 SCORE2+MedicalHistory                2.8463502 NA
372827 phecode_979-7 SCORE2+MedicalHistory                2.9463669 NA
372828 phecode_979-7 SCORE2+MedicalHistory                2.7780201 NA
372829 phecode_979-7 SCORE2+MedicalHistory                2.8520975 NA
372830 phecode_979-7 SCORE2+MedicalHistory                2.6400810 NA
372831 phecode_979-7 SCORE2+MedicalHistory                2.7465903 NA
372832 phecode_979-7 SCORE2+MedicalHistory                2.8113601 NA
372833 phecode_979-7 SCORE2+MedicalHistory                2.7303478 NA
372834 phecode_979-7 SCORE2+MedicalHistory                2.8062345 NA
       hrs_mh_sex phecode_string         phecode_category
1      NA         All-Cause Death        Death
2      NA         All-Cause Death        Death
3      NA         All-Cause Death        Death
4      NA         All-Cause Death        Death
5      NA         All-Cause Death        Death
6      NA         All-Cause Death        Death
7      NA         All-Cause Death        Death
8      NA         All-Cause Death        Death
9      NA         All-Cause Death        Death
10     NA         All-Cause Death        Death
11     NA         All-Cause Death        Death
12     NA         All-Cause Death        Death
13     NA         All-Cause Death        Death
14     NA         All-Cause Death        Death
15     NA         All-Cause Death        Death
16     NA         All-Cause Death        Death
17     NA         All-Cause Death        Death
18     NA         All-Cause Death        Death
19     NA         All-Cause Death        Death
20     NA         All-Cause Death        Death
21     NA         All-Cause Death        Death
22     NA         All-Cause Death        Death
23     NA         All-Cause Death        Death
24     NA         All-Cause Death        Death
25     NA         All-Cause Death        Death
26     NA         All-Cause Death        Death
27     NA         All-Cause Death        Death
28     NA         All-Cause Death        Death
29     NA         All-Cause Death        Death
30     NA         All-Cause Death        Death
⋮      ⋮          ⋮                      ⋮
372805 NA         Bone marrow transplant Stat
372806 NA         Bone marrow transplant Stat
372807 NA         Bone marrow transplant Stat
372808 NA         Bone marrow transplant Stat
372809 NA         Bone marrow transplant Stat
372810 NA         Bone marrow transplant Stat
372811 NA         Bone marrow transplant Stat
372812 NA         Bone marrow transplant Stat
372813 NA         Bone marrow transplant Stat
372814 NA         Bone marrow transplant Stat
372815 NA         Bone marrow transplant Stat
372816 NA         Bone marrow transplant Stat
372817 NA         Bone marrow transplant Stat
372818 NA         Bone marrow transplant Stat
372819 NA         Bone marrow transplant Stat
372820 NA         Bone marrow transplant Stat
372821 NA         Bone marrow transplant Stat
372822 NA         Bone marrow transplant Stat
372823 NA         Bone marrow transplant Stat
372824 NA         Bone marrow transplant Stat
372825 NA         Bone marrow transplant Stat
372826 NA         Bone marrow transplant Stat
372827 NA         Bone marrow transplant Stat
372828 NA         Bone marrow transplant Stat
372829 NA         Bone marrow transplant Stat
372830 NA         Bone marrow transplant Stat
372831 NA         Bone marrow transplant Stat
372832 NA         Bone marrow transplant Stat
372833 NA         Bone marrow transplant Stat
372834 NA         Bone marrow transplant Stat

In [12]:
unique(hrs$score)

[1] "ASCVD+MedicalHistory"
[2] "Age+Sex+Comorbidities+MedicalHistory"
[3] "Age+Sex+Comorbidities+MedicalHistoryLM"
[4] "Age+Sex+MedicalHistory"
[5] "Age+Sex+MedicalHistoryLM"
[6] "MedicalHistory"
[7] "MedicalHistoryLM"
[8] "QRISK3+MedicalHistory"
[9] "SCORE2+MedicalHistory"

In [13]:
purrr::map_dfr(integer(100), ~ hrs %>% group_by(endpoint, score) %>% sample_frac(1, replace=TRUE), .id="i") -> temp_hrs

In [14]:
library(ggdist)

Warning message:
“package ‘ggdist’ was built under R version 4.0.5”

In [15]:
temp_hrs_mh = temp_hrs %>% group_by(endpoint, score, phecode_string, phecode_category) %>% median_qi(hrs_mh, hrs_mh_age, hrs_mh_sex, na.rm=TRUE)

In [16]:
temp_hrs_linear = temp_hrs %>% ungroup() %>%
    filter(score %in% c("MedicalHistory", "Age+Sex+MedicalHistory", "Age+Sex+Comorbidities+MedicalHistory", "ASCVD+MedicalHistory")) %>%
    group_by(endpoint, score, phecode_string, phecode_category) %>% 
    median_qi(`hrs_mh`, na.rm=TRUE) %>% rename(hr = `hrs_mh`) %>%
    mutate(hr = round(hr, 2), .lower=round(.lower, 2), .upper=round(.upper, 2)) %>%#c(hr, .lower, .upper), round, 1) %>%
    mutate(HR_MedicalHistory = glue("{hr} ({.lower}, {.upper})")) %>% 
    select(endpoint, score, phecode_string, phecode_category, HR_MedicalHistory) %>%
    pivot_wider(names_from="score", values_from="HR_MedicalHistory") %>% 
    select(all_of(c("phecode_category", "endpoint", "phecode_string", "MedicalHistory", 'Age+Sex+MedicalHistory',  "Age+Sex+Comorbidities+MedicalHistory", "ASCVD+MedicalHistory"))) %>% 
    mutate(endpoint = factor(endpoint, levels = endpoint_order)) %>% 
    arrange(endpoint) %>%
    #mutate(endpoint = recode(endpoint, !!!endpoint_map)) %>%
    ungroup()
    
temp_hrs_linear

     phecode_category endpoint
1    ID               phecode_001
2    ID               phecode_002
3    ID               phecode_002-1
4    ID               phecode_003
5    ID               phecode_004
6    ID               phecode_004-1
7    ID               phecode_004-2
8    ID               phecode_004-3
9    ID               phecode_005
10   ID               phecode_005-1
11   ID               phecode_005-2
12   ID               phecode_007
13   ID               phecode_007-1
14   ID               phecode_008
15   ID               phecode_009
16   ID               phecode_010
17   ID               phecode_011
18   ID               phecode_012
19   ID               phecode_015
20   ID               phecode_015-2
21   ID               phecode_019
22   ID               phecode_020
23   ID               phecode_020-1
24   ID               phecode_024
25   ID               phecode_025
26   ID               phecode_030
27   ID               phecode_050
28   ID               phecode_050-4
29   ID               phecode_052
30   ID               phecode_052-1
⋮    ⋮                ⋮
1854 Preg             phecode_930
1855 Preg             phecode_932
1856 Preg             phecode_938
1857 Preg             phecode_940
1858 Rx               phecode_965
1859 Rx               phecode_965-5
1860 Rx               phecode_969
1861 Rx               phecode_973
1862 Rx               phecode_974
1863 Rx               phecode_975
1864 Rx               phecode_975-2
1865 Rx               phecode_975-23
1866 Rx               phecode_976
1867 Rx               phecode_977
1868 Rx               phecode_977-1
1869 Rx               phecode_977-11
1870 Rx               phecode_977-4
1871 Rx               phecode_977-41
1872 Rx               phecode_977-5
1873 Rx               phecode_977-51
1874 Rx               phecode_977-52
1875 Rx               phecode_977-7
1876 Rx               phecode_977-71
1877 Rx               phecode_977-72
1878 Stat             phecode_978
1879 Stat             phecode_978-2
1880 Stat             phecode_979
1881 Stat             phecode_979-2
1882 Stat             phecode_979-7
1883 Death            OMOP_4306655
     phecode_string
1    Salmonella
2    Staphylococcus
3    Staphylococcus aureus
4    Escherichia coli
5    Streptococcus
6    Streptococcus pneumoniae
7    Group A Streptococcus
8    Group B Streptococcus
9    Mycobacteria
10   Mycobacterium tuberculosis
11   Nontuberculous mycobacteria
12   Hemophilus infection
13   Hemophilus influenzae
14   Helicobacter [H. pylori]
15   Pseudomonas
16   Corynebacterium
17   Klebsiella
18   Proteus
19   Clostridium
20   Clostridium difficile
21   Treponema
22   Borrelia
23   Lyme disease
24   Pertussis
25   Enterococcus
26   Campylobacter
27   Enterovirus
28   Hand, foot, and mouth disease
29   Herpesvirus
30   Herpes simplex
⋮    ⋮
1854 Maternal care for abnormality of pelvic organs
1855 Known or suspected fetal abnormality affecting management of mother
1856 Other conditions or status of the mother complicating pregnancy, childbirth, or the puerperium
1857 Malposition and malpresentation of fetus
1858 Psychotropic agents causing adverse effects in therapeutic use
1859 Psychostimulants causing adverse effects in therapeutic use
1860 Adverse effects of agents primarily affecting gastrointestinal system
1861 Adverse effect of other drug
1862 Adverse effect of vaccine
1863 Primarily systemic agents causing adverse effects in therapeutic use
1864 Antineoplastic and immunosuppressive drugs causing adverse effects in therapeutic use
1865 Mucositis (ulcerative) due to antineoplastic therapy
1866 Adverse effect of anesthesia
1867 Long term (current) drug therapy
1868 Long term (current) use of anticoagulants and antithrombotics/antiplatelets
1869 Long term (current) use of anticoagulants
1870 Long term (current) use of steroids
1871 Long term (current) use of inhaled steroids*
1872 Long term (current) use of agents affecting hormones
1873 Long term (current) use of hormonal contraceptives
1874 Hormone replacement therapy (postmenopausal)
1875 Long term (current) use of insulin or oral hypoglycemic drugs
1876 Long term (current) use of insulin
1877 Long term (current) use of oral hypoglycemic drugs
1878 Tissue transplant or graft
1879 Corneal transplant or graft
1880 Transplated organ
1881 Kidney transplant
1882 Bone marrow transplant
1883 All-Cause Death
     MedicalHistory    Age+Sex+MedicalHistory
1    3.39 (2.73, 3.93) 3.4 (2.73, 3.95)
2    2.8 (2.65, 3)     2.78 (2.64, 2.96)
3    2.82 (2.63, 3.01) 2.81 (2.63, 3)
4    2.86 (2.69, 3.14) 2.77 (2.61, 3.04)
5    2.97 (2.73, 3.19) 2.95 (2.72, 3.2)
6    3.12 (2.85, 3.77) 3.13 (2.85, 3.75)
7    3.21 (2.85, 3.85) 3.18 (2.87, 4.01)
8    2.96 (2.73, 3.27) 2.93 (2.74, 3.26)
9    3.16 (2.87, 3.46) 3.23 (2.88, 3.46)
10   3.23 (2.95, 3.58) 3.22 (2.95, 3.56)
11   3.07 (2.85, 3.36) 3.04 (2.83, 3.35)
12   2.91 (2.78, 3.01) 2.89 (2.76, 2.98)
13   2.92 (2.77, 3.01) 2.9 (2.75, 2.98)
14   2.93 (2.67, 3.61) 2.98 (2.71, 3.6)
15   2.79 (2.61, 2.98) 2.74 (2.56, 2.93)
16   3.05 (2.62, 3.26) 3.73 (3.35, 4.05)
17   2.9 (2.55, 3.14)  2.84 (2.5, 3.08)
18   2.84 (2.71, 3.08) 2.82 (2.68, 3.05)
19   3.02 (2.76, 3.45) 2.95 (2.73, 3.37)
20   3.01 (2.82, 3.39) 2.99 (2.78, 3.31)
21   3.05 (2.73, 3.39) 3.06 (2.77, 3.4)
22   4.27 (3.45, 4.72) 4.34 (3.52, 5.06)
23   4.24 (3.47, 4.76) 4.41 (3.53, 5.08)
24   4.52 (3.8, 5.94)  4.56 (3.88, 5.93)
25   2.92 (2.76, 3.25) 2.86 (2.71, 3.18)
26   2.85 (2.61, 3.22) 2.89 (2.65, 3.25)
27   3.44 (2.72, 4.51) 3.54 (2.83, 4.59)
28   5.13 (3.51, 7.9)  5.24 (3.82, 7.44)
29   2.58 (2.49, 2.8)  2.59 (2.44, 2.76)
30   2.48 (2.3, 2.64)  2.47 (2.33, 2.64)
⋮    ⋮                 ⋮
1854 4.59 (4.31, 5.95) 3.65 (3.33, 4.65)
1855 3.82 (3.49, 4.26) 2.67 (2.27, 2.99)
1856 3.52 (3.28, 3.87) 3.17 (2.85, 3.6)
1857 3.68 (3.31, 4.13) 3.52 (3.18, 3.91)
1858 4.49 (4.08, 5.52) 4.51 (4.11, 5.54)
1859 4.59 (4, 6.1)     4.58 (4.05, 6.11)
1860 2.72 (2.49, 2.83) 2.66 (2.47, 2.82)
1861 2.78 (2.55, 3.01) 2.74 (2.51, 2.95)
1862 3.4 (2.8, 4.6)    3.58 (2.89, 5.18)
1863 3.32 (3.09, 3.72) 3.34 (3.12, 3.73)
1864 3.32 (3.09, 3.72) 3.34 (3.12, 3.73)
1865 3.33 (3.09, 3.72) 3.34 (3.12, 3.73)
1866 3.78 (2.99, 5.75) 3.87 (3.08, 5.63)
1867 2.74 (2.63, 2.85) 2.74 (2.65, 2.86)
1868 2.88 (2.7, 3.13)  2.87 (2.7, 3.13)
1869 2.88 (2.71, 3.14) 2.86 (2.71, 3.14)
1870 2.57 (2.5, 2.76)  2.58 (2.51, 2.77)
1871 2.57 (2.5, 2.76)  2.58 (2.51, 2.77)
1872 2.86 (2.73, 3.06) 1.96 (1.88, 2.01)
1873 2.96 (2.83, 3.15) 2.13 (2.08, 2.23)
1874 3.05 (2.85, 3.35) 2.26 (2.11, 2.34)
1875 2.4 (2.29, 2.51)  2.4 (2.31, 2.52)
1876 2.41 (2.29, 2.51) 2.41 (2.29, 2.52)
1877 2.4 (2.28, 2.53)  2.41 (2.29, 2.54)
1878 0.48 (0.01, 3)    0.02 (0, 2.89)
1879 0.24 (0, 2.88)    2.75 (0, 2.93)
1880 2.48 (2.33, 2.62) 0.7 (0.15, 2.55)
1881 2.41 (2.26, 2.55) 2.41 (2.26, 2.54)
1882 2.8 (2.64, 2.96)  2.83 (2.66, 2.99)
1883 2.85 (2.76, 2.98) 2.7 (2.61, 2.81)
     Age+Sex+Comorbidities+MedicalHistory ASCVD+MedicalHistory
1    3.4 (2.75, 3.86)                     3.41 (2.71, 3.87)
2    2.94 (2.83, 3.22)                    2.86 (2.74, 3.07)
3    3.01 (2.82, 3.25)                    2.9 (2.71, 3.14)
4    2.9 (2.73, 3.19)                     2.77 (2.62, 3.02)
5    3.18 (2.91, 3.49)                    3.03 (2.8, 3.26)
6    3.41 (3.1, 4.14)                     3.11 (2.81, 3.71)
7    3.63 (3.19, 4.32)                    3.45 (3.07, 4.1)
8    3.14 (0.54, 3.54)                    3.1 (2.9, 3.51)
9    3.4 (3.07, 3.68)                     3.01 (1.74, 3.34)
10   3.33 (3.04, 3.84)                    2.97 (2.72, 3.34)
11   3.25 (2.95, 7.49)                    3.01 (2.82, 3.33)
12   3.09 (2.93, 3.19)                    2.88 (0.59, 2.94)
13   3.08 (2.91, 3.19)                    2.88 (2.73, 2.95)
14   3.01 (2.77, 3.65)                    2.79 (2.57, 3.23)
15   2.83 (2.66, 3.08)                    2.77 (2.6, 2.97)
16   3.7 (3.34, 4.08)                     3.72 (3.33, 4.09)
17   3.06 (2.66, 3.3)                     2.91 (2.56, 3.13)
18   2.99 (2.81, 3.16)                    2.93 (2.75, 3.09)
19   3.23 (2.92, 3.74)                    3.06 (2.77, 3.45)
20   3.22 (2.96, 3.65)                    3.01 (2.8, 3.36)
21   3.75 (3.33, 4.01)                    3.62 (3.16, 3.84)
22   4.42 (3.58, 5.15)                    4.34 (3.49, 5.06)
23   4.46 (3.59, 5.18)                    4.38 (3.51, 5.08)
24   4.52 (3.88, 5.89)                    4.46 (3.77, 5.83)
25   3.25 (3.06, 3.57)                    3.02 (2.81, 3.28)
26   2.93 (2.67, 3.28)                    2.87 (2.64, 3.2)
27   3.6 (2.88, 4.73)                     3.53 (2.79, 4.53)
28   5.17 (3.88, 7.93)                    5.2 (3.83, 7.83)
29   2.58 (2.43, 2.73)                    2.59 (2.45, 2.75)
30   2.47 (2.32, 2.64)                    2.46 (2.32, 2.62)
⋮    ⋮                                    ⋮
1854 3.69 (3.36, 4.65)                    3.54 (3.23, 4.4)
1855 2.69 (2.3, 3.06)                     2.65 (2.26, 3.02)
1856 3.17 (2.88, 3.61)                    3.16 (2.81, 3.56)
1857 3.47 (3.17, 3.87)                    3.45 (3.14, 3.83)
1858 5.42 (4.68, 6.58)                    4.7 (4.15, 5.66)
1859 6.02 (4.88, 8.31)                    4.66 (4.08, 6.24)
1860 2.64 (2.52, 2.82)                    2.67 (2.51, 2.82)
1861 2.85 (2.63, 3.2)                     2.8 (2.61, 3.13)
1862 3.7 (3.04, 5.27)                     3.63 (2.93, 5.18)
1863 4.12 (3.78, 5)                       3.33 (3.12, 3.74)
1864 4.13 (3.78, 5)                       3.33 (1.35, 3.74)
1865 4.12 (3.78, 4.99)                    3.33 (3.12, 3.74)
1866 3.91 (3.2, 5.71)                     3.61 (3, 5.54)
1867 2.72 (2.63, 2.85)                    2.72 (2.63, 2.84)
1868 2.96 (2.77, 3.29)                    2.86 (2.71, 3.12)
1869 2.96 (2.78, 3.3)                     2.88 (2.72, 3.13)
1870 2.59 (2.52, 2.8)                     2.58 (2.51, 2.77)
1871 2.59 (2.52, 2.8)                     2.58 (2.51, 2.77)
1872 1.96 (1.88, 2.01)                    1.93 (1.85, 1.97)
1873 2.13 (2.08, 2.23)                    2.12 (2.07, 2.22)
1874 2.25 (2.1, 2.34)                     2.19 (2.05, 2.27)
1875 2.38 (2.26, 2.43)                    2.23 (2.13, 2.28)
1876 2.13 (1.79, 2.2)                     2.09 (1.78, 2.24)
1877 2.41 (1.77, 2.5)                     2.23 (1.75, 2.3)
1878 2.88 (2.74, 3.01)                    2.88 (2.73, 3.01)
1879 2.86 (2.64, 2.97)                    2.86 (2.66, 2.98)
1880 2.63 (2.47, 2.82)                    0.32 (0.01, 2.65)
1881 2.43 (2.28, 2.59)                    2.39 (2.26, 2.54)
1882 3.13 (2.87, 3.28)                    2.8 (2.64, 2.99)
1883 2.76 (2.68, 2.89)                    2.68 (2.59, 2.78)

In [18]:
temp_hrs_linear %>% arrange(as.character(endpoint))

     phecode_category endpoint
1    Death            OMOP_4306655
2    ID               phecode_001
3    ID               phecode_002
4    ID               phecode_002-1
5    ID               phecode_003
6    ID               phecode_004
7    ID               phecode_004-1
8    ID               phecode_004-2
9    ID               phecode_004-3
10   ID               phecode_005
11   ID               phecode_005-1
12   ID               phecode_005-2
13   ID               phecode_007
14   ID               phecode_007-1
15   ID               phecode_008
16   ID               phecode_009
17   ID               phecode_010
18   ID               phecode_011
19   ID               phecode_012
20   ID               phecode_015
21   ID               phecode_015-2
22   ID               phecode_019
23   ID               phecode_020
24   ID               phecode_020-1
25   ID               phecode_024
26   ID               phecode_025
27   ID               phecode_030
28   ID               phecode_050
29   ID               phecode_050-4
30   ID               phecode_052
⋮    ⋮                ⋮
1854 Preg             phecode_908
1855 Preg             phecode_930
1856 Preg             phecode_932
1857 Preg             phecode_938
1858 Preg             phecode_940
1859 Rx               phecode_965
1860 Rx               phecode_965-5
1861 Rx               phecode_969
1862 Rx               phecode_973
1863 Rx               phecode_974
1864 Rx               phecode_975
1865 Rx               phecode_975-2
1866 Rx               phecode_975-23
1867 Rx               phecode_976
1868 Rx               phecode_977
1869 Rx               phecode_977-1
1870 Rx               phecode_977-11
1871 Rx               phecode_977-4
1872 Rx               phecode_977-41
1873 Rx               phecode_977-5
1874 Rx               phecode_977-51
1875 Rx               phecode_977-52
1876 Rx               phecode_977-7
1877 Rx               phecode_977-71
1878 Rx               phecode_977-72
1879 Stat             phecode_978
1880 Stat             phecode_978-2
1881 Stat             phecode_979
1882 Stat             phecode_979-2
1883 Stat             phecode_979-7
     phecode_string
1    All-Cause Death
2    Salmonella
3    Staphylococcus
4    Staphylococcus aureus
5    Escherichia coli
6    Streptococcus
7    Streptococcus pneumoniae
8    Group A Streptococcus
9    Group B Streptococcus
10   Mycobacteria
11   Mycobacterium tuberculosis
12   Nontuberculous mycobacteria
13   Hemophilus infection
14   Hemophilus influenzae
15   Helicobacter [H. pylori]
16   Pseudomonas
17   Corynebacterium
18   Klebsiella
19   Proteus
20   Clostridium
21   Clostridium difficile
22   Treponema
23   Borrelia
24   Lyme disease
25   Pertussis
26   Enterococcus
27   Campylobacter
28   Enterovirus
29   Hand, foot, and mouth disease
30   Herpesvirus
⋮    ⋮
1854 Edema, proteinuria and hypertensive disorders in pregnancy, childbirth and the puerperium
1855 Maternal care for abnormality of pelvic organs
1856 Known or suspected fetal abnormality affecting management of mother
1857 Other conditions or status of the mother complicating pregnancy, childbirth, or the puerperium
1858 Malposition and malpresentation of fetus
1859 Psychotropic agents causing adverse effects in therapeutic use
1860 Psychostimulants causing adverse effects in therapeutic use
1861 Adverse effects of agents primarily affecting gastrointestinal system
1862 Adverse effect of other drug
1863 Adverse effect of vaccine
1864 Primarily systemic agents causing adverse effects in therapeutic use
1865 Antineoplastic and immunosuppressive drugs causing adverse effects in therapeutic use
1866 Mucositis (ulcerative) due to antineoplastic therapy
1867 Adverse effect of anesthesia
1868 Long term (current) drug therapy
1869 Long term (current) use of anticoagulants and antithrombotics/antiplatelets
1870 Long term (current) use of anticoagulants
1871 Long term (current) use of steroids
1872 Long term (current) use of inhaled steroids*
1873 Long term (current) use of agents affecting hormones
1874 Long term (current) use of hormonal contraceptives
1875 Hormone replacement therapy (postmenopausal)
1876 Long term (current) use of insulin or oral hypoglycemic drugs
1877 Long term (current) use of insulin
1878 Long term (current) use of oral hypoglycemic drugs
1879 Tissue transplant or graft
1880 Corneal transplant or graft
1881 Transplated organ
1882 Kidney transplant
1883 Bone marrow transplant
     MedicalHistory    Age+Sex+MedicalHistory
1    2.85 (2.76, 2.98) 2.7 (2.61, 2.81)
2    3.39 (2.73, 3.93) 3.4 (2.73, 3.95)
3    2.8 (2.65, 3)     2.78 (2.64, 2.96)
4    2.82 (2.63, 3.01) 2.81 (2.63, 3)
5    2.86 (2.69, 3.14) 2.77 (2.61, 3.04)
6    2.97 (2.73, 3.19) 2.95 (2.72, 3.2)
7    3.12 (2.85, 3.77) 3.13 (2.85, 3.75)
8    3.21 (2.85, 3.85) 3.18 (2.87, 4.01)
9    2.96 (2.73, 3.27) 2.93 (2.74, 3.26)
10   3.16 (2.87, 3.46) 3.23 (2.88, 3.46)
11   3.23 (2.95, 3.58) 3.22 (2.95, 3.56)
12   3.07 (2.85, 3.36) 3.04 (2.83, 3.35)
13   2.91 (2.78, 3.01) 2.89 (2.76, 2.98)
14   2.92 (2.77, 3.01) 2.9 (2.75, 2.98)
15   2.93 (2.67, 3.61) 2.98 (2.71, 3.6)
16   2.79 (2.61, 2.98) 2.74 (2.56, 2.93)
17   3.05 (2.62, 3.26) 3.73 (3.35, 4.05)
18   2.9 (2.55, 3.14)  2.84 (2.5, 3.08)
19   2.84 (2.71, 3.08) 2.82 (2.68, 3.05)
20   3.02 (2.76, 3.45) 2.95 (2.73, 3.37)
21   3.01 (2.82, 3.39) 2.99 (2.78, 3.31)
22   3.05 (2.73, 3.39) 3.06 (2.77, 3.4)
23   4.27 (3.45, 4.72) 4.34 (3.52, 5.06)
24   4.24 (3.47, 4.76) 4.41 (3.53, 5.08)
25   4.52 (3.8, 5.94)  4.56 (3.88, 5.93)
26   2.92 (2.76, 3.25) 2.86 (2.71, 3.18)
27   2.85 (2.61, 3.22) 2.89 (2.65, 3.25)
28   3.44 (2.72, 4.51) 3.54 (2.83, 4.59)
29   5.13 (3.51, 7.9)  5.24 (3.82, 7.44)
30   2.58 (2.49, 2.8)  2.59 (2.44, 2.76)
⋮    ⋮                 ⋮
1854 3.98 (3.71, 4.71) 4 (3.35, 5.13)
1855 4.59 (4.31, 5.95) 3.65 (3.33, 4.65)
1856 3.82 (3.49, 4.26) 2.67 (2.27, 2.99)
1857 3.52 (3.28, 3.87) 3.17 (2.85, 3.6)
1858 3.68 (3.31, 4.13) 3.52 (3.18, 3.91)
1859 4.49 (4.08, 5.52) 4.51 (4.11, 5.54)
1860 4.59 (4, 6.1)     4.58 (4.05, 6.11)
1861 2.72 (2.49, 2.83) 2.66 (2.47, 2.82)
1862 2.78 (2.55, 3.01) 2.74 (2.51, 2.95)
1863 3.4 (2.8, 4.6)    3.58 (2.89, 5.18)
1864 3.32 (3.09, 3.72) 3.34 (3.12, 3.73)
1865 3.32 (3.09, 3.72) 3.34 (3.12, 3.73)
1866 3.33 (3.09, 3.72) 3.34 (3.12, 3.73)
1867 3.78 (2.99, 5.75) 3.87 (3.08, 5.63)
1868 2.74 (2.63, 2.85) 2.74 (2.65, 2.86)
1869 2.88 (2.7, 3.13)  2.87 (2.7, 3.13)
1870 2.88 (2.71, 3.14) 2.86 (2.71, 3.14)
1871 2.57 (2.5, 2.76)  2.58 (2.51, 2.77)
1872 2.57 (2.5, 2.76)  2.58 (2.51, 2.77)
1873 2.86 (2.73, 3.06) 1.96 (1.88, 2.01)
1874 2.96 (2.83, 3.15) 2.13 (2.08, 2.23)
1875 3.05 (2.85, 3.35) 2.26 (2.11, 2.34)
1876 2.4 (2.29, 2.51)  2.4 (2.31, 2.52)
1877 2.41 (2.29, 2.51) 2.41 (2.29, 2.52)
1878 2.4 (2.28, 2.53)  2.41 (2.29, 2.54)
1879 0.48 (0.01, 3)    0.02 (0, 2.89)
1880 0.24 (0, 2.88)    2.75 (0, 2.93)
1881 2.48 (2.33, 2.62) 0.7 (0.15, 2.55)
1882 2.41 (2.26, 2.55) 2.41 (2.26, 2.54)
1883 2.8 (2.64, 2.96)  2.83 (2.66, 2.99)
     Age+Sex+Comorbidities+MedicalHistory ASCVD+MedicalHistory
1    2.76 (2.68, 2.89)                    2.68 (2.59, 2.78)
2    3.4 (2.75, 3.86)                     3.41 (2.71, 3.87)
3    2.94 (2.83, 3.22)                    2.86 (2.74, 3.07)
4    3.01 (2.82, 3.25)                    2.9 (2.71, 3.14)
5    2.9 (2.73, 3.19)                     2.77 (2.62, 3.02)
6    3.18 (2.91, 3.49)                    3.03 (2.8, 3.26)
7    3.41 (3.1, 4.14)                     3.11 (2.81, 3.71)
8    3.63 (3.19, 4.32)                    3.45 (3.07, 4.1)
9    3.14 (0.54, 3.54)                    3.1 (2.9, 3.51)
10   3.4 (3.07, 3.68)                     3.01 (1.74, 3.34)
11   3.33 (3.04, 3.84)                    2.97 (2.72, 3.34)
12   3.25 (2.95, 7.49)                    3.01 (2.82, 3.33)
13   3.09 (2.93, 3.19)                    2.88 (0.59, 2.94)
14   3.08 (2.91, 3.19)                    2.88 (2.73, 2.95)
15   3.01 (2.77, 3.65)                    2.79 (2.57, 3.23)
16   2.83 (2.66, 3.08)                    2.77 (2.6, 2.97)
17   3.7 (3.34, 4.08)                     3.72 (3.33, 4.09)
18   3.06 (2.66, 3.3)                     2.91 (2.56, 3.13)
19   2.99 (2.81, 3.16)                    2.93 (2.75, 3.09)
20   3.23 (2.92, 3.74)                    3.06 (2.77, 3.45)
21   3.22 (2.96, 3.65)                    3.01 (2.8, 3.36)
22   3.75 (3.33, 4.01)                    3.62 (3.16, 3.84)
23   4.42 (3.58, 5.15)                    4.34 (3.49, 5.06)
24   4.46 (3.59, 5.18)                    4.38 (3.51, 5.08)
25   4.52 (3.88, 5.89)                    4.46 (3.77, 5.83)
26   3.25 (3.06, 3.57)                    3.02 (2.81, 3.28)
27   2.93 (2.67, 3.28)                    2.87 (2.64, 3.2)
28   3.6 (2.88, 4.73)                     3.53 (2.79, 4.53)
29   5.17 (3.88, 7.93)                    5.2 (3.83, 7.83)
30   2.58 (2.43, 2.73)                    2.59 (2.45, 2.75)
⋮    ⋮                                    ⋮
1854 4.04 (3.31, 5.12)                    3.92 (3.33, 5.08)
1855 3.69 (3.36, 4.65)                    3.54 (3.23, 4.4)
1856 2.69 (2.3, 3.06)                     2.65 (2.26, 3.02)
1857 3.17 (2.88, 3.61)                    3.16 (2.81, 3.56)
1858 3.47 (3.17, 3.87)                    3.45 (3.14, 3.83)
1859 5.42 (4.68, 6.58)                    4.7 (4.15, 5.66)
1860 6.02 (4.88, 8.31)                    4.66 (4.08, 6.24)
1861 2.64 (2.52, 2.82)                    2.67 (2.51, 2.82)
1862 2.85 (2.63, 3.2)                     2.8 (2.61, 3.13)
1863 3.7 (3.04, 5.27)                     3.63 (2.93, 5.18)
1864 4.12 (3.78, 5)                       3.33 (3.12, 3.74)
1865 4.13 (3.78, 5)                       3.33 (1.35, 3.74)
1866 4.12 (3.78, 4.99)                    3.33 (3.12, 3.74)
1867 3.91 (3.2, 5.71)                     3.61 (3, 5.54)
1868 2.72 (2.63, 2.85)                    2.72 (2.63, 2.84)
1869 2.96 (2.77, 3.29)                    2.86 (2.71, 3.12)
1870 2.96 (2.78, 3.3)                     2.88 (2.72, 3.13)
1871 2.59 (2.52, 2.8)                     2.58 (2.51, 2.77)
1872 2.59 (2.52, 2.8)                     2.58 (2.51, 2.77)
1873 1.96 (1.88, 2.01)                    1.93 (1.85, 1.97)
1874 2.13 (2.08, 2.23)                    2.12 (2.07, 2.22)
1875 2.25 (2.1, 2.34)                     2.19 (2.05, 2.27)
1876 2.38 (2.26, 2.43)                    2.23 (2.13, 2.28)
1877 2.13 (1.79, 2.2)                     2.09 (1.78, 2.24)
1878 2.41 (1.77, 2.5)                     2.23 (1.75, 2.3)
1879 2.88 (2.74, 3.01)                    2.88 (2.73, 3.01)
1880 2.86 (2.64, 2.97)                    2.86 (2.66, 2.98)
1881 2.63 (2.47, 2.82)                    0.32 (0.01, 2.65)
1882 2.43 (2.28, 2.59)                    2.39 (2.26, 2.54)
1883 3.13 (2.87, 3.28)                    2.8 (2.64, 2.99)

In [19]:
temp_hrs_linear  %>% 
    write_csv("outputs/SupplTable6_HRsAll.csv")